### ISSUE TITLE
As a user, I want to change how the list of references is sorted so that I can browse the list in different ways

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#100]
## Notes for testing
Test site updated 10/10 with fix for author sort issue.

sort on:
- page order in derrida work
- author of cited work
- title of cited work

**Comment by araiffe** [comment]
@rlskoeser @kac3 I note that when citing by Author name, there is an incoherency between first name/last name sorting. I suspect this is a data clean-up issue, but it exists nonetheless. If it's just that, we can flag this as tested and closed.

**Comment by rlskoeser** [comment]
@araiffe it looks to me like the code is sorting on the correct field.  Could you provide an example of where you're seeing the discrepancy so I can check if it's something data cleanup will fix or if there's something I missed?

**Comment by araiffe** [comment]
@rlskoeser see example below (p. 1)
Abbé Dubos followed by Abraham, then Stender-Peterson, then Ajuriaguerra, then Espinas,…

![screen shot 2017-10-10 at 14 58 31](https://user-images.githubusercontent.com/26753387/31404972-973065f2-adcb-11e7-8d9a-f84ee80ddc4f.png)

**Comment by kevinglover** [comment]
@rlskoeser It looks like it's sorting based on Abbè, Abraham, Adolf, Ajuriaguerra, Alfred...

**Comment by rlskoeser** [comment]
Ha!  I was sorting on the tokenized version of the field and not the exact, untokenized version (something that haystack obscures a bit, I think).  I guess it was sorting on any name that included an A anywhere. 

@araiffe thanks for catching this and clarifying it with specifics!
