### ISSUE TITLE
As a user, I want to search across library works, references, interventions, and essays so that I can find content that interests me across types of material.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#101]
## Notes for testing
Use the search icon at the top right; make sure the right-side is set to All and not a specific subtype.

**Comment by araiffe** [comment]
@rlskoeser  This doesn't seem to be working: I can't get it to perform the search by clicking enter and there is no "submit" button. Am I doing something wrong?

**Comment by rlskoeser** [comment]
@araiffe this should be fixed in Safari now; please test again.

**Comment by araiffe** [comment]
I tested this and confirm it is now working in Safari.
