### ISSUE TITLE
As a user, I want to optionally select one content type so that I can restrict my search to a single set of materials on the site.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#102]
## Notes for testing
When you use the main search, if you select a specific content type you should go directly to the search results for that one kind of material, skipping over the multi-search page with results for each type.

**Comment by rlskoeser** [comment]
This is working with existing content types, but won't be done until we have Outwork.

**Comment by araiffe** [comment]
@rlskoeser I can't get the website to actually perform a search at all (enter doesn't work, there is no button to get it to perform i can see)

**Comment by rlskoeser** [comment]
@araiffe what browser are you using?  Hitting the enter key is working for me in Chrome and Firefox.  What page were you on when you tried to search?  

I'll also ask @xinyil what she thinks about adding a submit button (although using the enter key should still work).

**Comment by araiffe** [comment]
@rlskoeser I'm using Safari and confirm that today it is still not working. 
I tried Opera and it is working in Opera. Maybe the problem is just an incompatibility with Safari?

**Comment by rlskoeser** [comment]
@araiffe thanks for checking and reporting back.  It must indeed be something different about Safari!  Now that we have that detail we'll be better able to look into it.

Will you be able to do testing with another browser, or will this problem continue to be a blocker for testing?

**Comment by araiffe** [comment]
@rlskoeser I can definitely test in Opera, it's not a problem. Feel free to mark this as closed if you want to create another separate issue for the Safari problem. I tested this feature in Opera and it seems to be working.

**Comment by rlskoeser** [comment]
@araiffe great idea!  I will create a new ticket for the safari search issue and ask Kevin to take a look.  If you've tested this feature (now that you can search) and you're satisfied with it, please close it when you get the chance.
