### ISSUE TITLE
As a user searching across all site materials, I want to access all results for a single kind of item so that I can see more results.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#103]
## Notes for testing
After you search across all site materials, you should see a link for each type that will let you view all the results for that type of content.  It should preserve your search terms.

**Comment by rlskoeser** [comment]
Working for everything but Outwork, which is not yet implemented.

**Comment by araiffe** [comment]
@rlskoeser not changing the label on this one, but as per my prior comments, I can't seem to get the website to perform a search at all. Will test once that's resolved.

**Comment by araiffe** [comment]
Tested and works.
