### ISSUE TITLE
As a user, I want to filter intervention search results so that I can narrow the results by aspects of the annotation or annotated work.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#105]
## Notes for testing
- Updated version now integrates form filter into the same style of filters used elsewhere on the site.
- Use the main search to get to an intervention search result and then apply filters.
-----

- [x] add unstyled form and make sure filters are functional (RSK)
- [x] style form filters (KG)

Filter by:
- book author
- book subject
- book language of publication
- book original language
- book edition year
- annotation language
- annotation type
- annotation hand
- ink
- derrida work

**Comment by rlskoeser** [comment]
@kevinglover intervention search filters are working now - I went ahead and put the bare form in the template as you suggested so I could test the logic.  Ready for you to integrate into the filter drop-down interface.

**Comment by araiffe** [comment]
@rlskoeser Could you provide details on what steps I should take to test this feature? Thank you!

**Comment by araiffe** [comment]
@rlskoeser I'm not 100% clear on how #105 differs from #121

**Comment by rlskoeser** [comment]
@araiffe #121 is just changing the sort options; #105 is filtering the results base on the various facet fields.

**Comment by rlskoeser** [comment]
I think the unstyled form (and maybe duplicated form) is causing confusion or problems.  The filters seemed to work ok to me, but Alex reported strange results in his comments on #121.

@kevinglover I didn't have time to style the form properly, would you please handle it?

**Comment by araiffe** [comment]
Retested and seems to be working.
