### ISSUE TITLE
As a user looking at a single book, I want the option to sort references by page order in Derrida work or referenced book so that I can see them in either order.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#106]
## Notes for testing
As of 3/8/2018, has been updated so the sorting by page order in this work sorts properly 

--- 
- [x] add sort field variant for reference page number that indexes it as a number (strip out p, s, -##)

**Comment by araiffe** [comment]
There are some wonky issues here. Besides showing extraneous works, it's not sorting the pages in order under "Page order in this work". See screenshot attached. 
![screen shot 2017-10-21 at 11 39 25](https://user-images.githubusercontent.com/26753387/31853322-94c3935c-b654-11e7-8023-c2c4e9bef47e.png)

**Comment by rlskoeser** [comment]
This is filtering correctly on the test site now, but I'm not sure that sorting by page in current work is functioning properly because it's sorting on a string and not a number.
