### ISSUE TITLE
Typography - weight issue, Fonts not loading in Safari

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#107]
- Somehow Safari is not getting Sabon

- Book title and author are jumping to Bold in Georgia, set weight to 400
<img width="1416" alt="screen shot 2017-09-06 at 1 31 29 pm" src="https://user-images.githubusercontent.com/17734456/30126100-e4db9b2e-9308-11e7-8148-f6a7a365eb1f.png">

**Comment by kevinglover** [comment]
@xinyil I'm going to split this into two separate issues, so we can tackle them individually.
