### ISSUE TITLE
Typography - weight issue

### ISSUE THREAD

**Issue by kevinglover** [Princeton-CDH/derrida-django#108]
- Book title and author are jumping to Bold in Georgia, set weight to 400
<img width="1416" alt="screen shot 2017-09-06 at 1 31 29 pm" src="https://user-images.githubusercontent.com/17734456/30126100-e4db9b2e-9308-11e7-8148-f6a7a365eb1f.png">

**Comment by xinyil** [comment]
Book titles are been display in bold, probably because the style inherits 700 font-weight for heading?
