### ISSUE TITLE
Safari not loading Sabon

### ISSUE THREAD

**Issue by kevinglover** [Princeton-CDH/derrida-django#109]
@xinyil reported that Safari is not properly loading Sabon.

**Comment by rlskoeser** [comment]
@bwhicks any ideas?  I figured out how to turn on the Safari development tools and look at the web inspector - I don't see any errors for the font not loading.  

Xinyi's suggestion to me yesterday when we talked about testing the font was to comment out the first font in the styles and see if the display changes - and it does for me.  I can tell that e.g. the title on the home page looks different in Chrome and in Safari, but I'm not sure if it's the font not loading or some other detail in the display.

**Comment by xinyil** [comment]
Looks like it is loaded in Book page
https://test-derrida.cdh.princeton.edu/library/hegel-enzyklopadie-der-philosophischen-wissenschaften-im-grundrisse-1952/


<img width="1182" alt="screen shot 2017-09-08 at 12 49 39 pm" src="https://user-images.githubusercontent.com/17734456/30222154-40a285f8-9494-11e7-8694-8b7e1bcb798c.png">
<img width="1173" alt="screen shot 2017-09-08 at 12 49 58 pm" src="https://user-images.githubusercontent.com/17734456/30222156-4274c6b6-9494-11e7-9426-35a23bf84652.png">


The style of title, and author should be consistent on book page, library, and citation/annotation cards.

**Comment by rlskoeser** [comment]
Anyone know if this has been fixed?

**Comment by xinyil** [comment]
looks like Sabon is showed in Safari in some palces. Libray page book title and outwork summary page title is not being displayed in Sabon. 


this has not been fixed:
The style of title, and author should be consistent on book page, library, and citation/annotation cards.

<img width="1189" alt="screen shot 2017-11-13 at 11 25 08 am" src="https://user-images.githubusercontent.com/17734456/32736416-69ced0a8-c865-11e7-8a37-8e14dec79519.png">
<img width="896" alt="screen shot 2017-11-13 at 11 24 02 am" src="https://user-images.githubusercontent.com/17734456/32736417-6a0006aa-c865-11e7-86d5-892d700a6561.png">

**Comment by kevinglover** [comment]
@xinyil The size difference might have been based on a change in direction - the Book L mock has the title and author set to 19px and 18px respectively, but the M/S views are set to 15px/14px. The Other sections were being scaled based on the larger fonts, so it makes sense why they are off now.  I'll push the changes to make the fonts the right sizes.

**Comment by xinyil** [comment]
The size issue has been documented in a different issue. Closing.
