### ISSUE TITLE
As an admin I need a way to take down book or page images so that I can comply quickly with any requests from copyright holders.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#112]
## Notes for testing
- If you are a logged in user with permission to edit books, you should see an "admin actions" section in the left sidebar of the single page detail view with a form to suppress the current page or all pages in a book
- Please test suppressing a single page and suppressing all pages
- To stop suppressing images, you must edit the work instance in the admin site: you should see a checkbox for suppressing all images and another field where you can select or deselect specific images.
- View the page for a suppressed image in a different browser or after logging out: you should not see the image or deep zoom

**Comment by kac3** [comment]
@rlskoeser 

The take-down option should appear at the bottom of any page with an image of a page from a book.  

This link should take the user to a form that pre-populates with bibliographic info about the instance and has fields for the user to enter their name, contact, and text for their specific request (e.g., I am writing on behalf of x to request that you take down pp. 34-35 of y….).  The info from this form should then get forwarded to my email, with a copy to other concerned parties (I’ll maybe let you all figure out amongst yourselves who that should be at the CDH — Jean, maybe?).  Would I then go in and dissociate the relevant canvas or canvasses from references, so they no longer show up as large images?

If that does happen, perhaps we could display text along the lines of “This page cannot be displayed due to copyright restrictions. We encourage you to consult this volume on site at Princeton University Library."

**Comment by rlskoeser** [comment]
@kac3 and I discussed in person, documenting here for @jabauer to review.

I think we can just provide an email for contact, I only want to build the admin functionality side of this.

I like Katie's suggestion, take-down option should appear at the bottom of any content page with a full-size image from a book.  We will only display this for logged in admins - something like "suppress this page image".  We probably should also have an option to suppress all pages for a book.

My plan is to add a flag to the database to mark images that need to be suppressed, and to suppress the page image only - the detailed page view with documented annotations will still be displayed, just without the page image.  We can make the suppression flag editable in the admin so that it can be turned off if we get permission to put it back up or suppress something by mistake.

Assumptions:
- thumbnails are fine to show
- external images of the book are fine to show (thumbnail or full size)
- insertion images are fine to show because PUL owns copyright (thumbnail or full size)

Based on these assumptions, thumbnails, overview images, and insertion images will never be suppressed.

Only images for annotated pages will be accessible, so only a fraction of the total work will be public.

**Comment by jabauer** [comment]
That is a thorough and reasonable functionality.  It mitigates the legal risk, without over-complicating the feature set.

**Comment by rlskoeser** [comment]
@kevinglover please integrate this into the page view when you work on that (#125).  The view & template now includes a form to suppress content if the current user has appropriate permissions.  I've also added a context flag to indicate if an image is currently suppressed.  In that case, please display some kind of placeholder for the page image and disable deep zoom; but we still want all the annotation information to display.  (The images will be restricted at the view layer when they're suppressed, so you don't need to worry about security in the template.)

We were thinking the suppress form would go at the bottom - but if you come up with a place that works better that's fine with me.  (That's not where the logic is in the template right now, but that was just so I could test it more easily.) It would be great if you could also add some light styling to the form for consistency with the rest of the site, and also the message that displays after it's submitted (I took a first pass at that), but this is admin-only functionality so you probably shouldn't spend a lot of time on it.

**Comment by kac3** [comment]
@rlskoeser I'm seeing this option but for some reason I'm not able to actually click on it and get to the form.  Could this be a browser issue?  (I'm using Safari.)

**Comment by rlskoeser** [comment]
@kac3 I think what got built isn't exactly what I initially described (although the functionality is the same).  I've just added notes for testing to the issue description to try to clarify a bit more.  The form to suppress the current image or all images should be right there on the page in the left sidebar, if you are logged in and have the correct permissions.

It does look like the image is not actually being properly suppressed once you submit the form... If you would, please test the other functionality and see if there is anything else we need to address when we fix that.

**Comment by kac3** [comment]
@rlskoeser I managed to suppress some images yesterday, but when I went back to try it again now (to test in accordance with your updated notes), I find that once again I'm not able to click on "submit" to actually make the suppression happen.  I see it, but I can't select it.

https://test-derrida.cdh.princeton.edu/library/saussure-cours-de-linguistique-generale-1960/gallery/pbr86d472s/#annotations

![screen shot 2018-03-01 at 10 03 03 pm](https://user-images.githubusercontent.com/26174024/36881486-6016a086-1d9c-11e8-8309-3b1b90a588e9.png)

Weirdly, I'm having the same issue with other links on this page.  The page list in the side bar and the "deep zoom" toggle work fine, but nothing else is working: none of the menu links at the top (Reference List, etc.) or the Book Image Gallery link.  So maybe it's possible that the issue isn't this particular function but something else?  For what it's worth, I'm having the same problem in Safari and Chrome.

**Comment by rlskoeser** [comment]
@kac3 thanks for checking again and giving detailed feedback.  I noticed I couldn't click the menu links at the top as well, so something must be wrong with the styles on this page. We'll look into it!

**Comment by rlskoeser** [comment]
@kac3 I haven't been able to duplicate the problem you're getting where you can't click the submit button, but I have made some other updates:
- the page image and deep zoom are now suppressed properly after you mark it an item as suppressed (if you don't see it right away you may have to do a force reload in your browser, because it may be cached; use command+shift+r on a mac or control+shift+r on windows).  
- the annotation card has been modified based on the style changes you requested and that I discussed with Xinyi
- the list of pages on the left sidebar has been adjusted based on the style changes Xinyi recommended after seeing actual content - I don't know if this will have any impact on the submit button issue or not.

We haven't figured out how to fix the un-clickable nav links for this page, but we're looking into it.

The suppressed image display is provisional; I'll get Xinyi to provide something the right size.

**Comment by kac3** [comment]
@rlskoeser No longer having the issue where I can't click the submit button, but now I'm getting this error page when I do click it:
![screen shot 2018-03-28 at 2 26 16 pm](https://user-images.githubusercontent.com/26174024/38048709-1cb8fae8-3294-11e8-9b53-a618cd842a8e.png)

**Comment by rlskoeser** [comment]
@kac3 yes, I got an error email with more details about that - we'll look into it.  Thanks for documenting.

**Comment by kac3** [comment]
@rlskoeser Super, thanks.

I'm really liking all the changes Xinyi made, but I just noticed something peculiar about the display of the interventions on page view: they are currently displaying in reverse order, i.e., the ones at the top of the page show up at the bottom of the list and vice versa.  This screen shot should give you the idea.

![screen shot 2018-03-28 at 2 30 47 pm](https://user-images.githubusercontent.com/26174024/38049004-fe0a41e6-3294-11e8-9935-5a487a5c2c30.png)

**Comment by kac3** [comment]
@rlskoeser For some reason I'm still not able to click on "Submit" or select "all annotated pages in this volume."  Tested in both Safari and Chrome.

**Comment by kac3** [comment]
@rlskoeser Also still unable to click on menu items at top of page on page view ("Derrida's Library," "Reference List" et al.).

**Comment by thatbudakguy** [comment]
should now be unblocked by #151
