### ISSUE TITLE
Typography - text underline 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#115]
<img width="255" alt="screen shot 2017-09-08 at 11 56 53 am" src="https://user-images.githubusercontent.com/17734456/30220443-6b1e9328-948d-11e7-881c-b38d6ba80b15.png">

Text underline is getting into the defenders and blocking text in next line.

We might wan to increase line-height or try something mentioned in this reference to work around descenders:
https://css-tricks.com/styling-underlines-web/

**Comment by kevinglover** [comment]
@xinyil How about this? I increased the line-height to 1.4
<img width="211" alt="screen shot 2017-09-13 at 6 50 36 pm" src="https://user-images.githubusercontent.com/2983582/30404396-7ce2f20e-98b4-11e7-8ada-7555e04c606f.png">

**Comment by xinyil** [comment]
Can we add 1.3px bottom padding so the defenders don't touch the underline? and change line-height to 1.5 to give is a bit more space.
<img width="1102" alt="screen shot 2017-11-22 at 3 14 05 pm" src="https://user-images.githubusercontent.com/17734456/33147995-078d628a-cf98-11e7-9549-dd9721e982f0.png">
