### ISSUE TITLE
Typography - bold style usage 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#116]
If a typeface has it's own bold weight, don't let the browser determine the font weight.

Notice how blur the text in navigation are, and that alphabets are bumping into each other in the built:
<img width="1156" alt="screen shot 2017-09-08 at 11 53 54 am" src="https://user-images.githubusercontent.com/17734456/30220596-fd479fce-948d-11e7-909b-1535171b4fc3.png">

Modify font family names should fix this:
<img width="1158" alt="screen shot 2017-09-08 at 11 53 12 am" src="https://user-images.githubusercontent.com/17734456/30220611-0cab5d16-948e-11e7-940b-8bd5b03f25cb.png">

substitution could be "Georgia-Bold"

**Comment by xinyil** [comment]
![screen shot 2017-09-25 at 3 35 58 pm](https://user-images.githubusercontent.com/17734456/30827195-567bb612-a207-11e7-966f-ed13abeb0323.png)

- Worked in Safari
- in Chrome somehow the text are really blurred

**Comment by xinyil** [comment]
navigation links work in Safari and chrome. looks like the active page title is having the same problem, and it can't be clicked on book page?
<img width="1317" alt="screen shot 2017-10-09 at 11 46 40 am" src="https://user-images.githubusercontent.com/17734456/31346614-aba46e3c-ace7-11e7-870d-3cdb3fcd5b8a.png">

**Comment by xinyil** [comment]
The top page name is still having the same bolded problem as the navigation links use to have: it's bolded by adding outline by the browser, not calling the actual bold weight of the font - alphabets are bumping into each other.

**Comment by kevinglover** [comment]
@xinyil Not sure how you are getting that on the top page name? Looks like it is using the font-family bold and the font-weight is set to normal...

<img width="450" alt="screen shot 2017-10-16 at 2 12 30 pm" src="https://user-images.githubusercontent.com/2983582/31627721-34f6c0d8-b27c-11e7-9990-e830fbcf04f3.png">
<img width="539" alt="screen shot 2017-10-16 at 2 12 54 pm" src="https://user-images.githubusercontent.com/2983582/31627719-34ec1b4c-b27c-11e7-92ed-4992f28da9ba.png">

**Comment by xinyil** [comment]
ah it's letter spacing!

**Comment by xinyil** [comment]
- I can't get to the values, says the style is inherited, but it definitely looks bolder than the navigation title in both Sarafi and Chrome.
- remove letter spacing  
- substitution font should also be the bold one such as  "Georgia-Bold"

**Comment by kevinglover** [comment]
@xinyil I believe you are seeing some odd issues with the differing bold based on your .mov, but I am not able to replicate it at all! I have updated the letter-spacing and tried to find the closest web fonts available for the -Bold, -Italic. Those aren't common typesets for the web... typically there would be a basic Family and with different styles included, not a completely separate set dedicated for a style. I tested and found that `Georgia-Bold` and `Georgia-Italic` are available as well as `Helvetica-Bold` and `Helvetica-Oblique` (I know oblique isn't the same as italics, but there wasn't a `Helvetica-Italic` that loaded). Arial doesn't have separate sets at all, so I substituted with `Tahoma-Bold`. I was unable to find a sans-serif font that had an italic or oblique set.

**Comment by xinyil** [comment]
@kevinglover Thanks for diving into of world of fonts!
Many sans-serif typefaces only have _Oblique_, that's just slanted shape from roman, so they don't have a whole set of glyphs that are designed to be _italic_ like Humanist sans-serif typefaces do.
Verdana-italic seems to work, although I don't know if we should add italics when calling the font. Do you find browser handle italic style well?

**Comment by kevinglover** [comment]
@xinyil Browsers seem to handle italics fairly well, although not when we explicitly set a glyph set (a italic font-family with an italic font-style). That's where we got the odd rendering of fonts that were extra bold or had a text outline. Since we are taking the route of setting the font-family for each type, we just have to adhere to that pattern for the fallback font stack. If we are confident the embedded webfonts will load, then this is more of a precaution.

**Comment by xinyil** [comment]
Adding `-webkit-font-smoothing: antialiased` will fix the issue. 

a post on this:
http://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

> WebKit gives designers three font smoothing modes:

Nothing, which gives you jagged fonts
Subpixel-rendering, i.e. the default font smoothing mode that is used for most other stuff on your desktop OS (mobile devices don’t use subpixel rendering due to having to suport both vertical and horizontal screen orientations)
Antialiased, which disables subpixel-rendering and smoothes the font on the level of the pixel, as opposed to the subpixel.

![antialiased](https://user-images.githubusercontent.com/17734456/36498487-670b293e-170c-11e8-90e7-182f0de39f1d.png)

I tried in Chrome, and it will solve #143 as well.
We might still declare default weight and style to normal (see comment in #143 ).

**Comment by thatbudakguy** [comment]
@xinyil just to confirm - we want to try this on all light-on-dark text?

**Comment by xinyil** [comment]
@thatbudakguy that sounds right

**Comment by thatbudakguy** [comment]
the only place I know of this applies is to the homepage, where it affects just about everything. difference should be clearly visible now.
