### ISSUE TITLE
Document template components

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#117]
Please add a block comment at the top of any template components used in more than one place or for more than one variation in display to indicate where it is used, what context variables are expected, any different modes etc.  

I know this includes book-list-item, not sure if there are others.

This is important because we may now have some templates that sometimes have a solr result and sometime have a django model.  I can do the work to make them compatible, but it would help to know what the contexts and variations are.

**Comment by thatbudakguy** [comment]
@rlskoeser should we reassess the priority of this?

**Comment by rlskoeser** [comment]
@thatbudakguy I started documenting some of it; I'll try to add a bit more before we finalize the release
