### ISSUE TITLE
Display indicator when filters are active

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#118]
The search filter should have an indicator when there are filters active.  See the Filter Panel Collapsed section in Zeplin page for Elements / Forms.

**Comment by xinyil** [comment]
<img width="1410" alt="screen shot 2017-10-09 at 10 48 48 am" src="https://user-images.githubusercontent.com/17734456/31344153-cfb37ff0-acdf-11e7-91b3-7509e4bd5d5c.png">

- In safari, the filter icon is extra small in large viewport. When scaling the window down, it will jump to  the correct size. Behaves as expected in Chrome.

- displaying the expand button is the rollover status. perhaps slide from the top?

**Comment by kevinglover** [comment]
@xinyil Looks like that was a bug in Safari - the browser doesn't seem to handle SVGs as gracefully as Chrome. I went back through and refactored the form to work better in Safari as seen in below:

![form-hide-show-animation](https://user-images.githubusercontent.com/2983582/31463724-2252c23e-ae9d-11e7-94ff-8ed1ada81da8.gif)

**Comment by rlskoeser** [comment]
Looks good to me.  Tested in Chrome, Firefox, Safari.
