### ISSUE TITLE
As a user, I want the option to sort interventions by author or title of annotated work so I can look at them in different ways.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#121]

**Comment by rlskoeser** [comment]
Design indicates they should also be sortable by number of annotations, but I don't know what that means.

**Comment by rlskoeser** [comment]
@kevinglover sort may already be styled fine once you remove the placeholder form and finish the styles for #105, but I'm going to go ahead and leave this open and assign to you to confirm.

**Comment by araiffe** [comment]
Tested and this works.

**Comment by rlskoeser** [comment]
@araiffe your other comments indicated you weren't able to get to the intervention search, so I'm not sure how you could have tested it.  Did you misread it or close it by mistake?

**Comment by araiffe** [comment]
@rlskoeser I went to Reference List, clicked "Contains Annotations" as a filter, and sorted using "Author of cited work" and "Title of cited work". I didn't realize I was sorting based on search results using the search bar…

**Comment by rlskoeser** [comment]
@araiffe sorry it wasn't clear - this is about sorting interventions search results (which I don't think you've seen yet) rather than the references.  Thanks for explaining the steps you took.

**Comment by araiffe** [comment]
This is kind of weird, but if you search for all interventions (nothing in the search bar, "Interventions" selected, push enter), the system shows 29 results for Heidegger. But then when you check Heidegger and push submit, it gives 0 results. 
![screen shot 2017-10-24 at 11 43 20](https://user-images.githubusercontent.com/26753387/31953234-ac0bd5c0-b8b0-11e7-84b3-5c24eb58e273.png)

**Comment by rlskoeser** [comment]
The filters have been integrated properly into the filter bar, and the author filter looks to me like it's working properly.

**Comment by araiffe** [comment]
I retested this and now it works properly.
