### ISSUE TITLE
As a user I want to visualize and filter years by range so I can get an idea of the distribution and filter items by ranges of years.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#122]
## Testing Notes:
Some suggestions for testing this functionality
- [ ] On the 'Library' page, try using the copyright, work, and print year filters to filter (both using the inputs and the bar chart display, setting both scenarios with a start year and some with an end year and/or both.
- [ ] Reference page will function similarly
- [ ] Intervention page will function similarly  

## Dev notes:

- [x] figure out how to get solr range facets via haystack (RSK)
- [x] configure forms and views to run solr range facets and support filtering by start/end year (RSK)
- [x] unit tests on solr backend code (RSK)
- [x] unit tests on view logic (RSK)
- [x] style range facets into widgets and add logic to submit selected range as start end (KG)
- [x] add range facets to reference list page
- [x] unit tests on reference range facets
- [x] add range facets to intervention search
- [x] unit tests on intervention search facets

This story is my interpretation of the functionality implied by the filter UI element.
<img width="577" alt="screen shot 2017-09-24 at 1 45 12 pm" src="https://user-images.githubusercontent.com/691231/30785081-a3165326-a12e-11e7-8d99-19f5e73d0827.png">
I assume the ideal functionality would be able to enter dates manually _or_ to select a range of years on the graph and then get an updated histogram for the selected range to allow drilling down.  (Although could also keep the full range and highlight the selected dates?)

I was looking into this and discovered that haystack doesn't actually support Solr range facets yet.  But there is an open pull request that we may be able to adapt from: https://github.com/django-haystack/django-haystack/pull/978 

Sample facet range output from Solr:

query options:
```
facet.range=work_year&facet=on&indent=on&q=*:*&rows=0&wt=json&facet.range.start=1600&facet.range.end=2017&facet.range.gap=50
```

facet range output:
```
facet_ranges: {
work_year: {
counts: [
"1600",
5,
"1650",
6,
"1700",
11,
"1750",
31,
"1800",
6,
"1850",
8,
"1900",
55,
"1950",
76,
"2000",
0
],
gap: 50,
start: 1600,
end: 2050
}
},
```

@kevinglover would appreciate your input on this.  Assuming I can get a Solr facet range from haystack, what would it take to implement this on the front-end ?  What is the best way to structure the data for display in a histogram?  How many bins of numbers would you want?

**Comment by kevinglover** [comment]
@rlskoeser That format will work well, we just need a count for the items in the year.

[Check out this demo for the histogram](https://codepen.io/kevinglover/pen/PJWzya) We can iterate over a set of year/value objects. Having a start/end value is really helpful

**Comment by rlskoeser** [comment]
@kevinglover demo looks good!  We can get start/end from the database or current range.

**Comment by rlskoeser** [comment]
@kevinglover the counts are the numbers between the years (not sure why Solr returns it like that).

**Comment by rlskoeser** [comment]
@kevinglover I have solr range faceting working in the `feature/solr-range-facet` branch.  I haven't written unit tests for the new logic yet, because I think the view logic may need to change some based on what you find out (although I could probably start writing tests for the solr backend code).  Please let me know if more tests for this code would be helpful/valuable for you before you dig in.  (I see the build is broken now, I'll fix that).

I've only implemented this on the Library view for now.  Once we're happy it's working properly there (and make any adjustments or fixes necessary), I can repeat the logic for the other views that need it.

Note that the start/end for the range facet will update based on user selected range when there are values submitted on the form.  Both start and end are optional, so you can get an open-ended range from beginning to date or date to end (in my tests this seems to be working fine).

**Please note**: I had to extend the default haystack SolrEngine to add support for range faceting, so for this to work you must change your haystack configuration to use `derrida.common.solr_backend.RangeSolrEngine`as your engine (I've updated the example localsettings to reflect this, but easy to miss on an update).

I've re-enabled the unstyled version of the form for testing purposes, so you should be able to see how it's working.

The facet range numbers are available in the template as `facets.ranges` (also noted there in a comment), and are structured like this now (note I've converted the flat list into two-tuples of value and count, which I hope will be easier to work with):
```
{'print_year': {'gap': 1, 'counts': [('1958', 0), ('1959', 0), ('1960', 0), ('1961', 0), ('1962', 0), ('1963', 0)], 'end': 1964, 'start': 1958}, 
'copyright_year': {'gap': 10, 'counts': [('1817', 1), ('1827', 0), ('1837', 0), ('1847', 0), ('1857', 0), ('1867', 0), ('1877', 0), ('1887', 0), ('1897', 0), ('1907', 0), ('1917', 0), ('1927', 1), ('1937', 3), ('1947', 16), ('1957', 36), ('1967', 2)], 'end': 1977, 'start': 1817}, 
'work_year': {'gap': 156, 'counts': [('-381', 5), ('-225', 0), ('-69', 0), ('87', 0), ('243', 0), ('399', 0), ('555', 0), ('711', 0), ('867', 0), ('1023', 0), ('1179', 0), ('1335', 0), ('1491', 2), ('1647', 10), ('1803', 28), ('1959', 18)], 'end': 2115, 'start': -381}}
```

**Comment by rlskoeser** [comment]
Finished adding the unit tests for my part of the code.

There was an error where `max` couldn't be calculated in some cases when running the tests so I tweaked it; not sure if it would ever cause a problem with real data.

**Comment by rlskoeser** [comment]
@xinyil this is working on the library page now, if you want to look and try it out.  I still have to add it to the reference list and interventions.

**Comment by kac3** [comment]
@rlskoeser Bar chart display seems to be working but unfortunately isn't super useful because almost all works are clustered at the end.

![screen shot 2018-03-30 at 11 18 00 am](https://user-images.githubusercontent.com/26174024/38142927-42e9d984-340c-11e8-8f64-e8d45ae76ce0.png)

(Also not sure what has a publication year of 2115! Obviously a data problem...)

**Comment by rlskoeser** [comment]
@kac3 did you try filtering the years? I expect the bar chart will be more useful when you're looking at a smaller range.  You can also click on one of the bars in the chart to select a range.

I looked into the numbers. For original publication year, we have a range from -381 to 1966.  When we send the range facet request, we have to specify a gap size to determine the number of bars in the chart; currently logic is to calculate it so we get 15.  In this case, that's a gap of 156 years.  Thats's where the 2115 is coming from - it's the end of that range based on the gap size, not based on our actual maximum.  Will this be acceptable if we adjust to display the actual maximum on the right?

**Comment by kac3** [comment]
@rlskoeser Yes, much more helpful once I narrow down the range! Looking great.

It would be terrific if we could adjust the latest date to the actual maximum -- that sounds like a perfect solution.

**Comment by rlskoeser** [comment]
@kac3 site has been updated so all range filters now display actual maximum year.  Thanks for catching that, seems much more useful now.

**Comment by kac3** [comment]
@rlskoeser Loving this change, and everything seems to be working great.
