### ISSUE TITLE
Revise IIIF image handling to use existing sizes available in the JP2

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#126]
- [x] retrieve the json, then find the closest image to the size we needed (the first size larger than desired size)
----

- calculate based on column size for largest max width (including gutters);
  - each size should also have a retina version = 2x

### small thumbnail
* related books, image gallery, annotation card, reference card
* 2 columns 

### large thumbnail
* library browse, cover on library detail view
* 3 columns

### large page image 
* not grid based ... ?

**Comment by rlskoeser** [comment]
Based on Fluid Grid Demo, max column width is 52.5 and max gutter size is 30px.

* small thumbnail: 2 columns + 1 gutter =  135px
  * 2x = 270px
* large thumbnail: 3 columns + 2 gutters = 217.5px (call it 218)
  * 2x = 435px

**Comment by rlskoeser** [comment]
@xinyil the large page image view does not seem to be grid based; the size in Zeplin has a width of 531px - is that about what you want?

Also I talked to the Library team about IIIF images best practices, and Jon said that if we want to be nice we could use the existing sizes that are specified in the image info, since "as those are the scales for which the jp2s are optimized".  Here are some example sizes:
```
sizes: [
  { width: 69, height: 113 },
  { width: 138, height: 225 },
  { width: 275, height: 450 },
  { width: 549, height: 900 },
  { width: 1097, height: 1800 },
  { width: 2193, height: 3600 },
  { width: 4385, height: 7200 }
]
```

I should be able to add logic to use the closest size larger than our calculated preferred size.

@xinyil @kevinglover what do you think?  Do you prefer exact sizes (and if so, why?) or are you comfortable with using existing sizes?

**Comment by xinyil** [comment]
The size is designed to enabling one to view the whole image without scrolling, if not in the deep zoom mode, so 700-900 px height is common.

We should call the img with doubled size for 2x screen? Or we can just use the 2x size.

We could try to restrict the height to 900px, and set auto width, using the 1800px height image. I think images come in different aspect ratios, are they?

**Comment by rlskoeser** [comment]
@xinyil ah, that makes sense to go by height instead of width then for the large image.

Since IIIF provides us whichever size we want, I think we should go ahead and provide the browser with both versions.

We definitely do have variation in aspect ratios, and there are some landscape images instead of portrait for the overview images.  That will mostly impact display on the gallery and the single page view for those images.

**Comment by rlskoeser** [comment]
@xinyil a lot of the images do have a size available with 900 px height, but I'm seeing some with heights in the 800s (827, 889) and at least one 700 (749).  If we set 900 as the min-height for the large page image, then we'll be loading roughly double that for the 1x on images that only have the 800 or 700 pixel tile size.  I think it's probably ok, just wanted to check with you - it's set as a variable, so if we want to set something smaller than 900 for the page image height it'll be pretty easy to adjust.

**Comment by rlskoeser** [comment]
Working in multiple dev environments and QA; chore, not end user testable.
