### ISSUE TITLE
Wording on homepage

### ISSUE THREAD

**Issue by araiffe** [Princeton-CDH/derrida-django#127]
@rlskoeser @xinyil I'm just noticing the following things on the home page that with @kac3 's permission should be changed. First of all, I'd like my name to appear as Alexander Baron-Raiffe. Secondly, I think that both "Graduate Research Assistants" and also "Advisors" ought to be pluralized with an "s" since there are multiple people in each category. Just a small remark but I noticed it this time when logging in.

**Comment by rlskoeser** [comment]
@araiffe Our plan is to make that page editable by the project team; what's there now is really placeholder content.  But your name should absolutely be listed the way you want it to be!

Thanks for calling our attention to this, though!
