### ISSUE TITLE
Revise filter form so it automatically submits when filters are changed

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#129]

**Comment by rlskoeser** [comment]
@xinyil - Kevin and I talked about the form behavior some, but it would be helpful if you would weigh in with what behavior you'd like to see and what you think makes sense.  Should the form submit after a brief delay? Or maybe when the input element loses focus?  If a delay, what kind of delay would work to allow clicking multiple filters without the form submitting without it feeling like it is too slow.

Should we have some visible indicator so users know the form is submitting?

There's currently a submit button on the form, but not in your design - Kevin says having two ways to submit is confusing so it sounds like we should remove that.  (Should we include it in a `<noscript>` tag for any kind of graceful degradation, or is that not a concern?  I don't know how functional the rest of the site or form filters will be without javascript.)

**Comment by xinyil** [comment]
Having a submit button for for the filters is confusing, and we can't provide meaning estimated numbers this way - the numbers are depended on the results of each other. 

I chatted with some designer friends and I think the easiest way to handle this would be to submit the form to the server when one dropdown menu is out of focus. Then estimated numbers in other filters could refresh based on the selection. It's very rare to see submit button in each dropdown form now, and people will get that it's auto submitting. If you think the responding time is long, we can consider adding a loading animation when the card section of the page is being refreshing.

@rlskoeser I'll leave it to you to decide if we'll include a submitting button for graceful degradation. You have better idea of whether other things will work in those scenarios.
