### ISSUE TITLE
citations: add/edit citation anchor text

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#13]
As a record editor, I want to be able to add new or edit citation anchor text in both French and English.

**Comment by kac3** [comment]
@bwhicks Ben, I apologize but I can't seem to find this function anywhere in the current database.  What we need is to be able to add the anchor text, i.e., the text from _De la grammatologie_, to each individual citation.

**Comment by bwhicks** [comment]
A mistaken click in this case. Sorry for the confusion! This is part of the next database phase.
