### ISSUE TITLE
javascript form filters: only include relevant, non-empty values in the query string 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#130]
Please revise the form submission logic so that only filters with values that are set and that are needed for filtering logic are included in the query string.  

In this example, I think only author should be included (and maybe the sort option - I'm ok with that being included even if it's the default):

<img width="1304" alt="screen shot 2017-10-05 at 3 53 57 pm" src="https://user-images.githubusercontent.com/691231/31249490-81515dca-a9e5-11e7-814e-8fd8076c022d.png">

**Comment by kevinglover** [comment]
@rlskoeser  This should be fixed in the feature/solr-range-facet branch. There was a conflict on the js with initializations. Let me know if you run into any issues.

**Comment by rlskoeser** [comment]
This is much better, thanks for fixing it.
