### ISSUE TITLE
Adjust cited in filter size so full title displays

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#136]
Please adjust this filter size so that the full title of _De la Grammatologie_ displays, instead of being cut off as it is here:

<img width="183" alt="screen shot 2017-10-09 at 11 37 16 am" src="https://user-images.githubusercontent.com/691231/31346185-439defbc-ace6-11e7-9ad3-c39ed0977faa.png">

**Comment by kevinglover** [comment]
@rlskoeser This is dependent on the width and the font-size of the filter component. I was looking into truncating the filter values if they were longer than the input, so it would look like "De la grammatolo..." Would that be acceptable?

**Comment by rlskoeser** [comment]
@kevinglover could we make an exception for this filter to make sure the full title displays?

@xinyil what do you think?

**Comment by kevinglover** [comment]
Would like ideas on how we could get all the titles to fit. We could change this field to be expandable, but we would have to decide how the filters would need to be adjusted

**Comment by xinyil** [comment]
It'd be good to make an exception for this filter. Maybe manually set the width so it displays the full title.

**Comment by kevinglover** [comment]
@xinyil It would be difficult to make the filter width dynamically change based on the size of the title. If `De la Grammatologie` will always be the longest title, we can set the width to the calculated size of "De la Grammatologie", but even that width may differ based on the font loaded. 

Another thing we could try would be to reduce the font-size of the filter.

**Comment by xinyil** [comment]
We don't need to make the width dynamically change. Just extend the size for this filter would be good. We could leave some Extra space for this one.

**Comment by kevinglover** [comment]
@xinyil Ok, that should be already merged in:
<img width="227" alt="screen shot 2017-10-11 at 1 48 34 pm" src="https://user-images.githubusercontent.com/2983582/31457489-ee4e4498-ae8a-11e7-92a8-a5ad13c32c17.png">

**Comment by rlskoeser** [comment]
Looks good.
