### ISSUE TITLE
Library - bookmark position

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#138]
book cover thumbnail width: 3 columns

bookmark label position: 10 px exceeding the top, 10 px to the right 
<img width="731" alt="screen shot 2017-10-09 at 1 21 01 pm" src="https://user-images.githubusercontent.com/17734456/31350452-43859f7a-acf5-11e7-9c7b-290b188ace4f.png">

**Comment by kevinglover** [comment]
@xinyil The difference in the position are due to the varying widths of the images. As you can see the _Tristes_ and _Anthropologie_ cover is narrower than the other. We have to decide whether we want to have the height or the widths consistent. Or we could just stretch the images to fit.

**Comment by xinyil** [comment]
consistent width and auto height is ideal

**Comment by kevinglover** [comment]
@xinyil Sure, but that's dependent on the images src, and the frontend styles can't handle it by itself. I have it so the widths will be consistent, since that's most important for the indicator. If all the images are formatted as the same dimension on the server, then the images will also have the same height.

**Comment by rlskoeser** [comment]
@kevinglover I have a task for myself to calculate what sizes we need (#126).  I could probably adjust this to constrain one dimension instead of both (I think I'm currently setting a max for either dimension, which in most cases ends up being the height).

**Comment by rlskoeser** [comment]
@kevinglover is this waiting on the image sizes or can you adjust to make width consistent instead of height?

**Comment by kevinglover** [comment]
@rlskoeser @xinyil Currently, we have it so the image is 100% width and auto height. If the thumbnail source images are sized identically (via the request), then they will all be the identical height. If we are ok with the what we have in QA, then we can close this card.

**Comment by rlskoeser** [comment]
Thanks for confirming @xinyil !  I think we agreed elsewhere that we would make images consistent in width and let the height vary based on the size of the original.  This should let you place the bookmark icon consistently.

I think this also means that any work I still need to do for generating IIIF images in different sizes shouldn't affect the display or behavior of this.  Please let me know if I'm wrong about that.
