### ISSUE TITLE
Search within dropdown 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#140]
<img width="1042" alt="screen shot 2017-10-16 at 2 37 21 pm" src="https://user-images.githubusercontent.com/17734456/31628763-b1182a1e-b27f-11e7-981f-c4306c406d9c.png">
<img width="1041" alt="screen shot 2017-10-16 at 2 37 41 pm" src="https://user-images.githubusercontent.com/17734456/31628766-b26b4e14-b27f-11e7-842b-edf665c216e4.png">

The instruction text block is blocking part of the outlines text field.

**Comment by xinyil** [comment]
This has not been fixed

**Comment by kevinglover** [comment]
@xinyil I'm not sure what needs to be addressed here

**Comment by xinyil** [comment]
See screenshots above: the instruction text block is blocking part of the outlines text field.
