### ISSUE TITLE
Search field status 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#141]
![screen shot 2017-10-16 at 2 41 32 pm](https://user-images.githubusercontent.com/17734456/31628964-35a6f1ac-b280-11e7-8eb7-706bed159061.png)

- Please refer to Zeplin for the status of search filed, and the hovering status of dropdown 

<img width="836" alt="screen shot 2017-10-16 at 2 44 01 pm" src="https://user-images.githubusercontent.com/17734456/31629064-8b3012b6-b280-11e7-9d77-84afbfbeeb21.png">

- can we use blue as the hovering status for search icon?

<img width="948" alt="screen shot 2017-10-16 at 2 44 09 pm" src="https://user-images.githubusercontent.com/17734456/31629094-a4ffe55e-b280-11e7-8f84-7d08cdd882a4.png">
- the icon at the left shouldn't be clickable
- ideally, when you expand the search field by clicking the search button at the top right, your cursor will focus on the field so you can start typing without clicking on the field again.

<img width="932" alt="screen shot 2017-10-16 at 2 44 20 pm" src="https://user-images.githubusercontent.com/17734456/31629189-e5f02eb6-b280-11e7-93a0-608905337210.png">
- don't need the lable

**Comment by kevinglover** [comment]
@xinyil We can definitely make it so the input is active when shown, change the placeholder text, and add padding?

There are a few minor issues with the spec as is when translating to the web:
* There is not a different on inputs between`with focus`and `active` - they are the same state
* It looks like there is a cursor on the "hover" state. For inputs, the cursor is only visible if the field is "active". 
* I'm not seeing the hover states for the dropdown menu. Let's add those so we are on the same page

As an aside, the icon is part of the `label`, which has the action of focusing in on the input. Making it focus on the input seemed like a better option than for it to be non-functional. However, we can disable that functionality too if you would like.

**Comment by xinyil** [comment]
- yes they are different states. I looked into this a while ago, and there isn't marjor benefit to visually differentiate the tow, a lot of design treat with focus and active the same.
- yes hovering won't activate the form

- Sorry  I seemed to use "active" differently! The last "active" row in spec means the search is functioning, but the text field is not active. It's how it looks when you are browsing the result, and text field is out of focus.

- I personally find the clickable search icon in front really confusing. When I first notice it's clickable, I don't know what the function is - submitting the form? reset the search? Let hold on this, I'd like to know how others react to this. The rounded background doesn't go with the rest of the site, if keeping it can we use blue as the hovering status for search icon?

**Comment by kevinglover** [comment]
@xinyil 

You are right that they are technically different states, but for inputs especially. `focus` typically is only the style you see when you use the `TAB` button to highlight the input. The `active` state is when you are typing - by default the browser doesn't even style this state. However, when you are typing the input is also in focus.

 Thanks for the clarification on the "Active" state. 

I can remove the circle for the icon and make it blue

**Comment by xinyil** [comment]
@kevinglover I'm following up on the search icon in front of the search field, people do confuse by what it does. Let's extend the text field line, and make the icon looks like a part of the search hint, but it won't go away as you type. It shouldn't be clickable. 

I update this in Zeplin elements/form.

<img width="788" alt="screen shot 2017-10-20 at 4 28 24 pm" src="https://user-images.githubusercontent.com/17734456/31840524-b9686fda-b5b3-11e7-8f86-1fc4bf1c2126.png">

**Comment by kevinglover** [comment]
@xinyil 👌

**Comment by xinyil** [comment]
It's not been fixed or not in the test site

**Comment by xinyil** [comment]
<img width="1155" alt="screen shot 2017-11-22 at 12 45 45 pm" src="https://user-images.githubusercontent.com/17734456/33142106-5ac40752-cf83-11e7-9436-161cee6c18f7.png">
<img width="1107" alt="screen shot 2017-11-22 at 12 47 11 pm" src="https://user-images.githubusercontent.com/17734456/33142107-5bd230c4-cf83-11e7-966e-dcf6cd861593.png">

- text field is still getting the focus bolded underlune and animation
- dropdown menu moved to a position on click
- rollover status doesn't match (see first comment)

**Comment by xinyil** [comment]
update after redeploying:

- dropdown misposition issues still exist
- can't collapse the dropdown menu by clicking the collapse button
- instructional text  "search" should be grey
- reduce pacing between dropdown items
- currently selected category should be blue
![search](https://user-images.githubusercontent.com/17734456/33146546-96f8dc98-cf92-11e7-83aa-c4058f02dda1.gif)


- display all the search categories all at once, there shouldn't be a scroll
- if the mouse moved out of the dropdown, should it collapse? the last hovered item is shown in a different grey now.

<img width="971" alt="screen shot 2017-11-22 at 2 28 16 pm 1" src="https://user-images.githubusercontent.com/17734456/33146512-68ef3522-cf92-11e7-87ad-a90f90c6ddea.png">

![search2](https://user-images.githubusercontent.com/17734456/33146851-d55a31e8-cf93-11e7-8fe6-cc4113b418e0.gif)

**Comment by xinyil** [comment]
The line of search field for normal status without focus should be grey. Please see screenshots above.

**Comment by xinyil** [comment]
<img width="824" alt="screen shot 2018-04-06 at 11 36 13 am" src="https://user-images.githubusercontent.com/17734456/38430391-218363b8-398f-11e8-8dd3-f67f56fdf414.png">
add white backgrund across SML please

**Comment by thatbudakguy** [comment]
This seems done? It appears grey on all pages except home.

**Comment by rlskoeser** [comment]
Text and underline for search bar without focus seems to be gray as desired.  However:

- [ ] search bar needs a white background; it is currently transparent; this is problematic when you scroll and particularly bad on the home page (not readable over the dark blue)
- [ ] the selected category for what content will be searched should be black and not grey

**Comment by thatbudakguy** [comment]
Search bar background looks good. However, when I select a category for what will be searched, previous selections retain the blue color, so it's possible to make the entire menu blue.
![screen shot 2018-10-08 at 9 57 10 am](https://user-images.githubusercontent.com/4924494/46613194-979e0200-cae0-11e8-947a-c7681997acc7.png)

**Comment by thatbudakguy** [comment]
Looks good now.
