### ISSUE TITLE
Filters - Drop down menu

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#142]
![screen shot 2017-10-16 at 2 49 19 pm](https://user-images.githubusercontent.com/17734456/31630041-64194604-b283-11e7-99b9-341bda5cca3f.png)
 
- See zeplin for the status of dropdown 
- add expande/collapse icon, see zeplin 
- clear all button is undelined 

![screen shot 2017-10-16 at 3 06 47 pm](https://user-images.githubusercontent.com/17734456/31630121-a74a8366-b283-11e7-83b3-678faef71e1a.png)
 toggle on its own row

![screen shot 2017-10-16 at 3 09 02 pm](https://user-images.githubusercontent.com/17734456/31630226-0683edc2-b284-11e7-9e9a-bb12a8ee9bb6.png)

- inactive filter icon would be blue as well, active one gets the red dot
- make the filter icon clickable

**Comment by xinyil** [comment]
<img width="261" alt="screen shot 2017-11-09 at 3 37 25 pm" src="https://user-images.githubusercontent.com/17734456/32628488-11afc2c8-c564-11e7-9cf8-8f5ca7ff3d73.png">
good call adding instruciong text! could we use "start" and "end"?
the text size looks large, but we might solve that by figuring out the em quesion in other issues.
enlarging the dropdown size would help.
also the rest of the feels too small - you can only see 3 options - we can increase the height of the dropdown menus.

**Comment by xinyil** [comment]
Above issues have not been fixed or not updated to test site? 

If we can't make "start" "end" fit, we can manually increase the width of the two date range filters?

**Comment by rlskoeser** [comment]
It looks to me like this is fixed in the latest code.

**Comment by xinyil** [comment]
Please note all the issues described in the first comment have not been fixed. Let me know if any further explanation is needed?

**Comment by xinyil** [comment]
update after redeploying:

- the normal state of the line should be grey
- the arrow icon is missing 
-reduce the spacing between toggles so they won't be broken into 2 lines on slighter smaller viewport (see screenshot)
<img width="1101" alt="screen shot 2017-11-22 at 1 45 40 pm" src="https://user-images.githubusercontent.com/17734456/33144638-b8b63fee-cf8b-11e7-9c16-b0244920b27d.png">

in S
- the filters are exceeding filter area
- can we stack the sorting options? so the text will appear to be underlined not the text block
<img width="503" alt="screen shot 2017-11-22 at 1 45 57 pm" src="https://user-images.githubusercontent.com/17734456/33144707-f56e7f14-cf8b-11e7-870e-bb0c87f36a13.png">

**Comment by xinyil** [comment]
- See zeplin for the status of dropdown,  the normal state of the line should be grey
- add expande/collapse icon, see zeppelin
- we don't need horizontal scroll bar
- can we make the scroll bar appear only when scrolling?
- tested on a different machine, and the menu still expands really slow - up to 2s delay, see video:
![screen shot 2018-02-21 at 11 52 24 am](https://user-images.githubusercontent.com/17734456/36493831-7ed4ec52-16fe-11e8-8316-a5e886091e07.png)

**Comment by xinyil** [comment]
![dropdown-list](https://user-images.githubusercontent.com/17734456/38214837-d827f088-3693-11e8-9833-5648aed3482f.gif)
this is a new glitch

**Comment by xinyil** [comment]
seems I can't click on the filter label or arrow to expand the menu, only clicking the white space below will expand the menu. tested on ipad, and it looks like the space below is treated like an input box, maybe that's why you can't "click into" the dropdown if not clicking on the box? and the "input area" appear to be a rounded box. same can be seen in the search field.

the collapse button should be blue.

![dropdown-click](https://user-images.githubusercontent.com/17734456/38431637-df475384-3992-11e8-8fae-fa772e609257.gif)

<img width="198" alt="screen shot 2018-04-06 at 12 01 04 pm" src="https://user-images.githubusercontent.com/17734456/38431650-e93e1260-3992-11e8-86fa-2ec232c88266.png">


![fullsizerender 2](https://user-images.githubusercontent.com/17734456/38431641-e1fd7234-3992-11e8-9d6e-cc2d28876fb8.jpg)
![fullsizerender](https://user-images.githubusercontent.com/17734456/38431644-e35c60c2-3992-11e8-87aa-748976ef8fff.jpg)

**Comment by rlskoeser** [comment]
Clicking on the arrow now opens a filter! 🎉 

However: clicking on the arrow for an open filter does nothing.

Also, according to Xinyi's comments the arrow should be blue when a filter is open.  I think  [elements/forms](zpl://screen?sid=59540f9db8636253cb5f27d7&pid=5953fc82bb0b6d162a13ff11) in Zeplin is the place to look.

**Comment by thatbudakguy** [comment]
Used a hilariously hacky fix to color the dropdown arrows because they're img tag SVGs; see [this article](https://medium.com/@union_io/swapping-fill-color-on-image-tag-svgs-using-css-filters-fa4818bf7ec6) for discussion.

**Comment by rlskoeser** [comment]
Filter arrow color and interaction look great.
