### ISSUE TITLE
Typography - extra outline of normal weight text

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#143]
Seems like some extra outline has been added to all the text, I think, maybe caused by some inherited material design style?

I've been suspected this for a long time, because a lot of the texts look bolder in the built than in the mockups. I thought it's just because browsers render typeface differently, untill I discovered this:
all the text on the page in lager viewport seems bolded, and when sized down to medium, they look normal, and become bold again in small.

Only text in medium viewport are right, others are fatty.

see the video:
https://files.slack.com/files-pri/T2VGMNE6T-F7K1JUH2P/download/extraoutlien.mov

**Comment by kevinglover** [comment]
@xinyil I cannot replicate this issue. Any styles added by the browser or material design should be repressed by the stylesheet. I tried resizing the homepage as well:

#Safari
![safari-desktop](https://user-images.githubusercontent.com/2983582/31633809-84972854-b28f-11e7-873a-1a493838fb69.gif)

#Chrome
![chrome-desktop](https://user-images.githubusercontent.com/2983582/31633893-a999f014-b28f-11e7-92bc-57587f415688.gif)

What browser version are you using?

**Comment by kevinglover** [comment]
@xinyil are you still experiencing this issue?

**Comment by xinyil** [comment]
Now text is consistent across viewport sizes, but they are HEAVIER than normal weight.
Previously, text in medium viewport is correct. 

We have solved a similar issue where the four corner navigation text is heavier. If you look at the library page and compare "Derrida's Library" in the navigation and at the top, you'll notice the top one is heavier with an outline. So the test in navigation is correct. I'm not clear what causes this. 

I'm ok if we document this as a separate issue, mark as unsolved and move on. It's not ideal, but if we can't make it right it's not the end of the world. What do you think? @rlskoeser

**Comment by rlskoeser** [comment]
@xinyil if it's minor enough that you can live with it, let's move on.  

@xinyil please go ahead and close this one and create an issue to document the remaining issue so we can keep it in mind whenever we revisit the styles for a future release.

**Comment by xinyil** [comment]
> A lot of the differences are more to do with the fact browsers add or omit different default weights / styles to fonts. To stop this happening make sure in your CSS you have font-weight: normal and font-style: normal in your @fontface code block.

We might want to try this.

**Comment by thatbudakguy** [comment]
@xinyil 
seems like we're already doing this - [see here](https://github.com/Princeton-CDH/derrida-django/blob/develop/sitemedia/scss/base/_variables.scss#L12-L36).

**Comment by thatbudakguy** [comment]
closing this in favor of #116 .
