### ISSUE TITLE
As an admin, I want to edit descriptions for dynamic list pages so that I can update wording without developer intervention.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#146]
## Notes for testing
- Text blurbs for library, reference list, interventions, and visualization are editable in the description section for the content page in the admin site.  Pages have been preloaded with the existing text content.
- I couldn't figure out a good way to make the links editable, so I'm leaving them hard-coded for now if that's ok.

**Comment by rlskoeser** [comment]
I couldn't figure out a good way to make the link and link text editable (the way they're currently formatted makes it a little more complicated, so I've simplified this to just editing the text description.

**Comment by kac3** [comment]
@rlskoeser This seems to be working for Library, Reference List, and Interventions, but strangely not for Visualization.  Not sure what's up.

**Comment by rlskoeser** [comment]
@kac3 thanks for catching that.  There were two things going on here:

1. I forgot to update the template for the visualization page to use the dynamic values from the database
2. I didn't account for the fact that there are actually two different visualization pages.  I've tweaked the migration so that the default initial pages create pages for both with the description text we had in place before.

**Comment by kac3** [comment]
@rlskoeser Working now!

Though on a separate note the visualization by chapter seems to have disappeared...?

**Comment by rlskoeser** [comment]
@kac3 yes, sorry about that - when we synchronized the test database with production data we lost the chapters (if you remember, the sections and chapters are editable in the backend).  I had a backup of the chapter data that I meant to restore but hadn't done so until today.
