### ISSUE TITLE
Outwork, possibly error page? - missing images and content, alignment issue

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#152]
<img width="1299" alt="screen shot 2017-11-09 at 3 00 30 pm" src="https://user-images.githubusercontent.com/17734456/32626980-e73d678e-c55e-11e7-8ca5-2769396ff053.png">
<img width="700" alt="screen shot 2017-11-09 at 3 01 37 pm" src="https://user-images.githubusercontent.com/17734456/32626981-e8a72d76-c55e-11e7-8f0d-8c0723bc1e6f.png">
- I'm getting this for the outwork page. is this the error page?
- image and text content are missing
- note that the content occupies 8 columns

**Comment by kevinglover** [comment]
@xinyil It looks like there aren't any outwork pages? It does bring up a question though - what should the outwork page look like if we don't have any pages? Or is that not a scenario we expect to see in production?

**Comment by xinyil** [comment]
<img width="1293" alt="screen shot 2017-11-09 at 3 47 53 pm" src="https://user-images.githubusercontent.com/17734456/32628910-668aec54-c565-11e7-9847-e75a68f14a9e.png">
I didn't get the styled 404, unless there is a different URL to test 404 page?

**Comment by kevinglover** [comment]
@xinyil This is the error page you get when in debug mode. You should be able to go to `/404` to see the styled error page.

**Comment by rlskoeser** [comment]
@xinyil I've added a test outwork page, please take another look at this.

**Comment by xinyil** [comment]
<img width="1149" alt="screen shot 2017-11-13 at 11 17 49 am" src="https://user-images.githubusercontent.com/17734456/32736168-c5626e1c-c864-11e7-94fa-971c7b6ac30f.png">
<img width="1192" alt="screen shot 2017-11-13 at 11 17 58 am" src="https://user-images.githubusercontent.com/17734456/32736169-c570e00a-c864-11e7-8f7b-c1cb1c39471c.png">

strangely I get different sized text for the year in Safari and Chrome.

**Comment by kevinglover** [comment]
@xinyil I'm not sure why it's not rending as Sabon for you in Safari.

Where you able to test the error page?

**Comment by xinyil** [comment]
404 page looks good. This one is for outwork page. Just noticed that the test and divider lines don't align.

**Comment by xinyil** [comment]
Why H3 is bolded while H2 is not? I'll update a page with 2 levels of subhead to Zeplin.

**Comment by thatbudakguy** [comment]
this is rending correctly for me in safari and firefox. @xinyil can you revisit it?

**Comment by xinyil** [comment]
@thatbudakguy typeface looks right! maybe is was caused by adding extra slanting by browser.

the title of outowork entry is in a different style though. and no need for underlining. 
<img width="1428" alt="screen shot 2018-04-02 at 1 55 16 pm" src="https://user-images.githubusercontent.com/17734456/38208081-d934a658-367d-11e8-9e78-d00ab1188980.png">

**Comment by thatbudakguy** [comment]
@xinyil ok; I'll take a look at it - thanks!

**Comment by rlskoeser** [comment]
@thatbudakguy FYI, the design includes an optional image on the list/card display, but we never implemented anything to provide the image

**Comment by xinyil** [comment]
If there won't be image then the text doesn't make sense to be shorter than the divider lines.
Will reassess the image thumbnail when #184 has been fixed.

**Comment by xinyil** [comment]
@thatbudakguy let’s remove the white space at right and center the text block of 5 columns

**Comment by xinyil** [comment]
<img width="1186" alt="screen shot 2018-04-05 at 12 24 40 pm" src="https://user-images.githubusercontent.com/17734456/38378635-55282334-38cc-11e8-9a4a-aa8e3dc5bd80.png">

**Comment by rlskoeser** [comment]
This is still a problem - second outwork stacks to the side instead of below.

**Comment by rlskoeser** [comment]
Second outwork now displays correctly under the first instead of stacking to the side.
