### ISSUE TITLE
No results - alignment, spacing above footer 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#153]
<img width="1301" alt="screen shot 2017-11-09 at 3 08 14 pm" src="https://user-images.githubusercontent.com/17734456/32627317-07025088-c560-11e7-9f31-b1333eff99f5.png">
- align the "no sentence" with the content width. 
- add 100px spacing above footer. this spacing should be universal across all the pages.

**Comment by kevinglover** [comment]
Just pushed some changes for this.
