### ISSUE TITLE
As a user, I want a way to link directly to a specific annotation so that I can cite or share that annotation.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#154]
## Notes for testing
- When you're looking at the individual page view, annotation cards will have a link icon that you can copy and use to cite or share.  When you load that url, you should see the page with that annotation highlighted.
- Selecting an annotation will also modify the url, so you can copy the url with an annotation selected and get the same behavior.

**Comment by kac3** [comment]
@rlskoeser I am successfully able to get the URL to change, so that I can copy and paste it to see the specific annotation highlighted.  But when I click on "permalink" I'm not seeing a link to copy and paste (other than the URL at the top of my browser).

**Comment by kac3** [comment]
@rlskoeser Ok, that makes sense!

I had tried opening the copied permalink in a new window and the annotation was indeed highlighted, so I think we should be able to close this issue now!
