### ISSUE TITLE
Deep zoom viewer does not close

### ISSUE THREAD

**Issue by kevinglover** [Princeton-CDH/derrida-django#157]
From the gallery page, open the deep zoom component. Select the option to full screen the viewer. The button to exit full screen does not trigger the close and result in an uncaught error.
```js
Uncaught TypeError: Cannot convert undefined or null to object
```

**Comment by rlskoeser** [comment]
@xinyil deep zoom viewer is updated on the test site with your latest icons.  The full screen mode exits fine with the button but not with the escape key - but I think maybe that's good enough for now, what do you think?

**Comment by xinyil** [comment]
@rlskoeser Having the button work is fine now. When I'm testing the test site, I feel if I click on the current "fit" one I'll exit full screen.
Maybe we need to change the "full screen" icon when in full screen, and have a different one for "fit".

**Comment by rlskoeser** [comment]
@xinyil changing icon isn't default behavior and I don't think we have time to add logic for that now.  If you want to supply a different icon you can - if you do and if possible, please update the template here as well as adding the svg file : https://github.com/Princeton-CDH/derrida-django/blob/develop/derrida/books/templates/books/public_canvas_detail.html#L362-L378

**Comment by rlskoeser** [comment]
@xinyil I'm going to close this since the deep zoom viewer close issue is resolved. We can update the icon if you like.

**Comment by xinyil** [comment]
@rlskoeser how about one for full screen, one for exit full screen, and another one for fit to screen?

**Comment by rlskoeser** [comment]
@xinyil nothing in the default seadragon config allows for that; I think it would be easier to add javascript to swap the two icons in place.

**Comment by xinyil** [comment]
@rlskoeser ok. I guess people can figure out when playing around with these buttons. we can include the icon swap on the wish list!
