### ISSUE TITLE
As a content manager, I want to be able to update the homepage content without requiring dev work or writing html

### ISSUE THREAD

**Issue by kevinglover** [Princeton-CDH/derrida-django#159]
## Notes for testing

All of the homepage content is now editable using the rich text editor. Two shortcuts have been added to the editor:

- "Credits", which inserts a set of role/name with the correct styling
- "Credit section", which inserts the wrapper for the credits, in case it was accidentally deleted.

**Comment by thatbudakguy** [comment]
All of the homepage content is now editable using the rich text editor. Two shortcuts have been added to the editor:
- "Credits", which inserts a set of role/name with the correct styling
- "Credit section", which inserts the wrapper for the credits, in case it was accidentally deleted.

The default text for the homepage and credits have been changed to the provided versions in [this document](https://docs.google.com/document/d/1YsAwaZLzt0ts-xAyKtTES9grMLRIS6r7VZuVC3V65fA/edit).
