### ISSUE TITLE
citations: associate with image/canvas

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#16]
As a record editor, I want to be able to associate a citation with one or more images from books so that I can track how citation of a particular page (or pages) relates to interventions on that page (or pages).

As a record editor, when editing this field in the Django admin, I want it to automatically filter to only those images associated with the digital edition of the book (i.e. if a reference is set to BookA, only images associated with BookA show up).

- [x]  revise help text to make it clear images are restricted to associated digitized volume
- [x] disable canvas select if no digitized volume is associated

**Comment by kac3** [comment]
@bwhicks @rlskoeser Not sure how to associate a given intervention or canvas. When I try to select either (either typing or via dropdown menu), I see "No results found."
![screen shot 2017-07-18 at 1 31 02 pm](https://user-images.githubusercontent.com/26174024/28315150-8c624460-6bbd-11e7-91b1-0ee3e5bb6ae2.png)

**Comment by bwhicks** [comment]
@kac3 Sorry about this one. It's a function of the import not being fully done while we're waiting on a dependency with Plum. In order to keep the autocomplete from being overwhelming, the search is limited to interventions or canvases related to the instance being examined. 

Right now it looks like `Les dieux et le destin en Babylonie`, `Pensée formelle et sciences de l'homme`, and `Essais et conférences` have digital editions associated with them, so if you select one of them from the instance drop down, you'll have access to all their canvases and interventions.

The same filter applies to the inline references displayed on an instance.

**Comment by rlskoeser** [comment]
@bwhicks perhaps we should disable the input if an item doesn't have a digital edition associated?  Maybe the help text could be revised to make this clearer, too.

**Comment by bwhicks** [comment]
@rlskoeser I like this on both suggestions. Fairly straightforward issue to solve, I think (famous last words).

**Comment by rlskoeser** [comment]
I'm going to mark as rejected and document the changes we want to make.
