### ISSUE TITLE
Citation card grid setting

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#161]
<img width="574" alt="screen shot 2017-12-27 at 4 52 39 pm" src="https://user-images.githubusercontent.com/17734456/34394335-80011dfc-eb26-11e7-933c-9f86f6a1f5ad.png">
<img width="592" alt="screen shot 2017-12-27 at 4 52 46 pm" src="https://user-images.githubusercontent.com/17734456/34394336-815fe55c-eb26-11e7-8a37-5df5a9e59685.png">
<img width="589" alt="screen shot 2017-12-27 at 4 52 59 pm" src="https://user-images.githubusercontent.com/17734456/34394337-821113d6-eb26-11e7-9f4a-bc2e21f98f69.png">
The text part on citation/annotation cards appear to be too narrow, and leaves extra space between text and thumbnail image. The narrow column makes it harder to read.
Text should occupy 4 columns, and the thumbnail image should align to the left of the next column, 200 px fix height.

**Comment by thatbudakguy** [comment]
think I've solved this using CSS grid. hooray!

**Comment by rlskoeser** [comment]
@thatbudakguy can we just do a 60% (or whatever) and not worry about making it grid exact?

Problem is the card layouts are used in multiple different variants and I don't think it's documented

**Comment by thatbudakguy** [comment]
![screen shot 2018-04-02 at 4 11 12 pm](https://user-images.githubusercontent.com/4924494/38213784-7faa7d7a-3690-11e8-8972-9deb3e4c2052.png)
