### ISSUE TITLE
Filters - going back is not cleaning filters, but the results have been cleaned

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#162]
![screen shot 2018-01-03 at 3 36 22 pm](https://user-images.githubusercontent.com/17734456/34538828-ff2aad62-f09b-11e7-817b-ad34b92b4973.png)

- see that linguistics is active in the subject filter
- the results are not been filtered to linguistics books

how to reproduce:
select any filter>go back

**Comment by bwhicks** [comment]
This is browser behavior for back and forward for the text inputs since they're never really submitted. @rlskoeser Found a fix that can go at the top of `site.js` that does an initial clear of the fields which are then set by Kevin's code properly.

**Comment by bwhicks** [comment]
@xinyil This one is back for you to take a look at when you have time. The inputs should set correctly and clear on back button.

**Comment by xinyil** [comment]
Thank you! It's working as expect. Closing.
