### ISSUE TITLE
Check box - extra outline in chrome, MD ripple should be disabled

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#168]
- in chrome, selected checkbox has an extra outline in chrome
<img width="236" alt="screen shot 2018-03-07 at 5 03 10 pm" src="https://user-images.githubusercontent.com/17734456/37121366-d9cf4346-222a-11e8-8964-28ac1d354239.png">

- in both chrome and safari, when clikcing on a checkbox you'll still get the material design ripple effect, only partial because it was blocked by other elements. should be removed.

<img width="368" alt="screen shot 2018-03-07 at 5 12 02 pm" src="https://user-images.githubusercontent.com/17734456/37121458-2b25885e-222b-11e8-96af-3099424296d6.png">

**Comment by thatbudakguy** [comment]
n.b. don't think I've fixed the extra outline, if it still exists, but I couldn't see it if it does.

**Comment by xinyil** [comment]
<img width="259" alt="screen shot 2018-04-05 at 11 54 23 am" src="https://user-images.githubusercontent.com/17734456/38377238-71f3e1dc-38c8-11e8-9629-5016703a41f8.png">
it looks good now! the disabled checkbox has a different fill color. could you unit the color?

**Comment by xinyil** [comment]
well it's smooth in safari:
![checkbox-safari](https://user-images.githubusercontent.com/17734456/38377652-79aa0d9c-38c9-11e8-9d30-8a09b66a04f6.gif)

but in chrome, still seeing the ripple and white line (cause by misaligned fill and outline?):
![checkbox-2](https://user-images.githubusercontent.com/17734456/38377693-9e29e552-38c9-11e8-9a88-99a9426b03d1.gif)

I was naive thinking that I tested in safari and it should be fine in chrome!

**Comment by thatbudakguy** [comment]
can't duplicate the misalignment in chrome. gonna close this because i don't have time to investigate further.

**Comment by xinyil** [comment]
I have the most up-tp-date version of chorme.
Version 65.0.3325.181 (Official Build) (64-bit)
Moving this to wishlist
