### ISSUE TITLE
Filters - sequence issue and inconsistent UI language 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#169]
- the sequnce have been discussed and carefully arranged by the project team. notice that how they are currently implimented differently than the wirefram
- library page has some inconsistent UI language. should be Language of Publication and Original Language, same as in reference list.
built:
<img width="1077" alt="screen shot 2018-03-07 at 5 18 34 pm" src="https://user-images.githubusercontent.com/17734456/37121705-0f7576ae-222c-11e8-85e2-d9a4b30f6453.png">

spec:
<img width="907" alt="screen shot 2018-03-07 at 5 18 50 pm" src="https://user-images.githubusercontent.com/17734456/37121712-15993e76-222c-11e8-9951-a127497602aa.png">

- please check filters for all three pages
- are we not including publication types?

**Comment by kac3** [comment]
@rlskoeser @xinyil 

- Library page filter is looking good overall; need to make the following small changes (in bold):

Only show books:
Extant in Derrida's Library
**Containing annotations** (make "annotation" plural and correct spelling of containing)
Containing **insertions** (make "insertion" plural)

- Reference list -- a few changes:

**Only show cited books:** (delete "that")
Extant in Derrida's Library
**Containing annotations** (make "annotation" plural and correct spelling of containing)

**Only show references:** (make "reference" plural, delete "that")
**With corresponding annotation**

- Intervention filters: these are looking good as far as I'm concerned; there's some inconsistency in having "annotation type" when we're calling the broad category "interventions" (similar issue with References/citation type on the References page), but I think it is still user-friendly.

Please let me know if I've overlooked anything or if you see potential problems with any of these changes.

**Comment by thatbudakguy** [comment]
did some minimal work on this, but making the fields align to spec would probably take way more time than I have.

**Comment by xinyil** [comment]
I think it's good enough. Leaving it to @kac3 to test the UI language and sequence. I found some interaction issues that I'll address in #142

**Comment by rlskoeser** [comment]
Going to call this done for current phase.
