### ISSUE TITLE
Filters - logic and option number display 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#170]
I tested it again, it turned out that the logic is OR, but when selected one option, the total number of other options have been displayed as if it's AND. for example, when selected levi-strauss, all the other authors get a 0.

<img width="344" alt="screen shot 2018-03-12 at 3 09 14 pm" src="https://user-images.githubusercontent.com/17734456/37304347-ab6f0e88-2607-11e8-8c0d-4351bacf5f6d.png">

**Comment by rlskoeser** [comment]
@xinyil this is something I remember discussing with you.  I recall you said to go with 0 for display to make it clear that those authors were available for selection but not included in the current result set.

We could revisit, but I'm not sure how high the priority should be (depending on difficulty / what we want to change).

**Comment by xinyil** [comment]
@rlskoeser 
Yes I remember talking about whether refresh numbers in other dropdowns to reflect the changes of active filters. I remembered that we did not hide unavailable items and display 0. But in this case, a lot of the authors shouldn't be 0. 
 
Within one dropdown, 0 makes me feel it's not available, and I wouldn't try to click on the ones with 0 till today I know it's been implemented as OR. Because it's OR, the numbers of one dropdown list should not change, even if some selections have been submitted. 

In this case, if I wanted to see works of Levi-strauss or Saussure, after selecting Levi-strauss, the numbers of other listings should not be 0.

**Comment by xinyil** [comment]
also noticed that there is a Saussure book in the library but Saussure is not in listed the author filter?

**Comment by rlskoeser** [comment]
@xinyil I've been thinking about this, but I don't know how to implement it with Solr facets and we don't have time to investigate and figure out a solution in the current phase.  If you have any suggestions for simple design change to make this less confusing in the short term, I'd be open to it, but otherwise I think we'll have to live with this for now and add it to our wishlist.

**Comment by thatbudakguy** [comment]
@xinyil do you have any ideas for how to make this less confusing design-wise? I don't think we have time at this point to implement the correct backend solution. I realize it's not ideal, but if you think doing something simple like hiding the numbers after one search would be better than nothing, I can do that.

**Comment by xinyil** [comment]
with the delayed submission it already feels better, and people can get accurate suggestion number at least for the first round of selecting. I can't think of a good way to improve it further. maybe hide numbers after the first form submission could avoid some confusion.

**Comment by thatbudakguy** [comment]
I can't think of a simple way to hide them after first submission, unfortunately, so I'm just gonna close this.
