### ISSUE TITLE
Filters - alphabetical index 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#171]
After clicking on an alphabet, the dropdown list scroll should jump to the start of the letter but the user can still scroll to the top and bottom beyond the selected alphabet. Currently the list is locked to the selected alphabet, and having to unselected before seeing other options seems inconvenient.
<img width="344" alt="screen shot 2018-03-12 at 3 17 21 pm" src="https://user-images.githubusercontent.com/17734456/37304619-7a035eb6-2608-11e8-9f40-34378478d7f7.png">

**Comment by rlskoeser** [comment]
Maybe slightly inconvenient, but works. Don't think we're going to revisit this one anytime soon.
