### ISSUE TITLE
Introduction text on banner - spacing and style 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#176]
- the spacing between the text box and the background should be 20px all sides

![screen shot 2018-03-28 at 4 20 10 pm](https://user-images.githubusercontent.com/17734456/38054203-47b359fe-32a4-11e8-94da-c12cbd1405f9.png)

- on library page, the instructional text should be in a different style than the abstract of the page. see zeplin.
- the link should be the same style as other sorting buttons
![screen shot 2018-03-28 at 4 23 33 pm](https://user-images.githubusercontent.com/17734456/38054347-b07a3534-32a4-11e8-94a7-d8d094163021.png)

- note that the background box has a slight transparency 
- need to move the position of the box on intervention page upwards, so it doesn't block the geek text saying "trace". see zeplin.
![screen shot 2018-03-28 at 4 30 19 pm](https://user-images.githubusercontent.com/17734456/38054556-56f2bba2-32a5-11e8-8264-7a9df81fc387.png)

**Comment by xinyil** [comment]
<img width="1180" alt="screen shot 2018-03-30 at 12 13 58 pm" src="https://user-images.githubusercontent.com/17734456/38144682-e2d42d62-3413-11e8-9e48-f1a0127ddc8a.png">

on Safari (left), the browser has added extra slanting feature to the italic style.

**Comment by thatbudakguy** [comment]
@xinyil should be fixed now

**Comment by xinyil** [comment]
this one has not been fixed:
- need to move the position of the box on intervention page upwards, so it doesn't block the geek text saying "trace". see zeplin.
screen shot 2018-03-28 at 4 30 19 pm


- change line-height to 1.2
<img width="1335" alt="screen shot 2018-04-02 at 10 25 32 am" src="https://user-images.githubusercontent.com/17734456/38200027-cd1f6c80-3660-11e8-82ca-a1d73e7f7235.png">


- reference page at M is not loading the banner image 
- see the line break at L, but remain as a single line at some sizes at M. can we line break for this page at L to aviod a typographic "widow"
<img width="1440" alt="screen shot 2018-04-02 at 10 26 08 am" src="https://user-images.githubusercontent.com/17734456/38200062-e58a701c-3660-11e8-8521-c5eff94a0834.png">
<img width="971" alt="screen shot 2018-04-02 at 10 29 17 am" src="https://user-images.githubusercontent.com/17734456/38200068-ea4a3fc4-3660-11e8-97a3-37a148cbbe00.png">

this might not relate to the original issue but just putting it here for now
- reference page at S uses a blurred image. did it load a 1x image for my 2x screen?
<img width="548" alt="screen shot 2018-04-02 at 10 35 10 am" src="https://user-images.githubusercontent.com/17734456/38200235-8aa49f78-3661-11e8-90dd-9663fde8114b.png">

**Comment by thatbudakguy** [comment]
- i don't think your screenshot of the intervention page posted, but i think i understood - moved it up so it's sort of "between" the text in the background image, but could move it further if need be
- line-height has been changed
- reference page is loading the image at M for me. can you try again & tell me what browser?
- not sure I understand about the line break. would we want it in all sizes *except* M? think this might be too complicated to implement for now.
