### ISSUE TITLE
search on reference should include author of referenced work

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#179]
From @kac3:
> When searching for references in the search bar at the top of the page, book sections don't show up in the results unless the author/title is in the anchor text of the reference. For example, if I search for "Février," I don't get the references that cite this section just by page number (such as the one on p. 20 above).

Another note from @kac3 #164 (comment)
> ... the reference search in general seems to be acting wonky. I just did a search for "Nietzsche" and came up only with results that have Nietzsche in the reference anchor text, but not the epigraph citing Nietzsche, La Naissance de la tragédie, on DG p. 15. (I know this is a different issue, but unsure where to put it!)

Support search by author or title of cited work or title of collected work that a book section appears in.

**Comment by rlskoeser** [comment]
@kac3 You were right about the reference search: I thought it included the author, but there was an error. That's been corrected, and I also added the collected work title for references to book sections.  Right now it only includes _either_ the instance title or the work title (which is often the same, but won't always be, e.g. for translations) - should it be updated to include both?  Should anything else from the referenced work be included?

**Comment by kac3** [comment]
@rlskoeser Great question -- let's go ahead have reference search include both work title and instance title.

Otherwise, this looks good!

**Comment by kac3** [comment]
@rlskoeser Tried searching for "Geburt," which appears in the work title of Nietzsche's _Birth of Tragedy_, and am getting no results.  Only getting results for the French instance title equivalent "Naissance."

**Comment by rlskoeser** [comment]
@kac3 sorry about that - I added the titles hastily and did it wrong.  Corrected the error and added a unit test to properly confirm the content included in default reference search - please try again.

**Comment by kac3** [comment]
@rlskoeser Thanks - working now!
