### ISSUE TITLE
people: add/edit roles types

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#18]
As a record editor, I want to add a new or edit an existing role type so that I can document the kinds of roles played by people associated with the Derrida Library.

**Comment by bwhicks** [comment]
Is there a controlled set of vocabulary that the team would like preloaded for this field?

**Comment by kac3** [comment]
There will be a set of vocabulary decided upon by the group, but the list has not yet been finalized. Is it possible to move forward and add the terms during data entry?

**Comment by bwhicks** [comment]
I see no reason why an initial list couldn't be added as a data fixture at a later point in the database development and QA cycle. 

I would be more concerned about adding a vocabulary list after data has hit production. (Better to try to standardize in QA.) If we need to think about this further, I am sure we can accommodate it though.

**Comment by kac3** [comment]
That makes good sense.  The team and I will get to work on finalizing these two lists.  Thanks!
