### ISSUE TITLE
reference card thumbnail display

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#183]
## Notes for testing

Reference card thumbnail behavior should be significantly improved.  The only ones without images now should be items not linked to a digitized edition; for volumes where Figgy labeling has not been completed we should get the designated manifest thumbnail image (usually the cover).  Please check and see if you see any other thumbnails beyond these that aren't displaying.

---

Initially documented by @kac3 on https://github.com/Princeton-CDH/derrida-django/issues/164#issuecomment-376021677

1. While some book section references do display thumbnails, some do not.  For the book section James Février, "Les Sémites et l'alphabet" (from _L'écriture et la psychologie des peuples_), for example, there are no thumbnail images displayed with the references, even when the pages referenced are annotated and show up in the image gallery on the book page.  (And we should at least get the book cover as a thumbnail when there is not annotated page image, yes?)

![screen shot 2018-03-25 at 8 38 19 pm](https://user-images.githubusercontent.com/26174024/37882145-b362e92c-306e-11e8-9418-727f2f4e697d.png)

![screen shot 2018-03-25 at 8 51 44 pm](https://user-images.githubusercontent.com/26174024/37882151-b8fe3f8a-306e-11e8-90eb-ceff7b6da77b.png)

I'm noticing that on the admin side this book section does is not listed as "is digitized," and I'm wondering if that's part of the issue.  But it's strange -- shouldn't a book section automatically be recognized as digitized when its "Collected in" instance is digitized? 

- The same issue exists with Vico, "Scienza Nuova" (cover should at least show here).

![screen shot 2018-03-25 at 9 00 21 pm](https://user-images.githubusercontent.com/26174024/37882292-14344ee8-3070-11e8-96cc-30311ab5b199.png)

- But this doesn't necessarily seem to be a section-specific issue.  There is no thumbnail for references to _L'écriture et la différence_, for example.
 
![screen shot 2018-03-25 at 9 10 07 pm](https://user-images.githubusercontent.com/26174024/37882386-ec8478cc-3070-11e8-80e3-f9f71b1582b4.png)

**Comment by rlskoeser** [comment]
I've improved the reference thumbnail display; previously it wasn't handling roman numeral page numbers or references with no book page; if there's no book page you should now see the cover.  It also skips anything that doesn't show as having a digital edition - the fix for book sections helps here, and there are still a few books that haven't been linked up with their digitized edition.

Note that reference page image is based on lookup by page number, so it will only work on Figgy items with updated page labels. However, we should get a cover if the specific page can't be found.

**Comment by kac3** [comment]
@rlskoeser Thumbnails are looking good!

Only remaining issue (different issue?) is that clicking on the thumbnail of a page image takes you to book view and not to that specific page view.  Is this fixable?

**Comment by rlskoeser** [comment]
@kac3 see the conversation on #85 - I think Xinyi and I have figured out a solution for this; I'll let you test the behavior on that issue when we get the new logic changed.

**Comment by rlskoeser** [comment]
@kac3 anything left to do on this one not covered by #85 ?

**Comment by kac3** [comment]
@rlskoeser I think we're good!
