### ISSUE TITLE
author dropdown menu incomplete

### ISSUE THREAD

**Issue by kac3** [Princeton-CDH/derrida-django#186]
The dropdown menu to sort by author is cutting off the end of the alphabet.  Documented in Library and Reference List.

![screen shot 2018-03-30 at 11 10 14 am](https://user-images.githubusercontent.com/26174024/38142797-c3990de4-340b-11e8-9034-8926bfb53ee1.png)
![screen shot 2018-03-30 at 11 03 59 am](https://user-images.githubusercontent.com/26174024/38142805-cb13d7f2-340b-11e8-9fc9-92ee3b747d0a.png)

**Comment by thatbudakguy** [comment]
@kac3 this is working correctly for me on citation/library/reference. perhaps fixed by other issues? would you mind trying it again?

**Comment by rlskoeser** [comment]
All authors are visible on filters for library, reference, and intervention.
