### ISSUE TITLE
Typography - em, type size on Chrome

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#188]
Just read it in #151 that Kevin set em to 14px, which by default is 16px. I wonder if it is not being applied and overwriting the browser default, and it is the cause of extra large types on Chrome?

everthing is larger on Chrome:
<img width="1431" alt="screen shot 2018-03-30 at 3 51 44 pm" src="https://user-images.githubusercontent.com/17734456/38151687-469d22e0-3432-11e8-9243-f089d608666a.png">

incorrect size resulting in misaligned lables:
<img width="307" alt="screen shot 2018-03-30 at 3 45 45 pm" src="https://user-images.githubusercontent.com/17734456/38151575-dcf7bf76-3431-11e8-9731-f38311001e3e.png">

**Comment by xinyil** [comment]
@thatbudakguy if you're looking at other typohraphy issues maybe you could help take a look at this?

**Comment by thatbudakguy** [comment]
@xinyil yeah, i'll look into this

**Comment by thatbudakguy** [comment]
it is being applied correctly, and it affects all browsers equally - if you set it to 16px all the text gets larger, including in chrome. I'm gonna close this bc whatever's going on in Chrome (if it's still happening) probably isn't related to setting the em value.

**Comment by thatbudakguy** [comment]
if by misaligned you mean the alignment of the text inside the "pill" not being centered, I think this is fixed in [this commit](https://github.com/Princeton-CDH/derrida-django/commit/f90260bd6881094c1cc22f6a46c9bc4496d30c8a), which should be in qa. if it doesn't look right still, let me know!
