### ISSUE TITLE
people: add/edit relationship types

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#19]
As a record editor,  I want to add a new or edit an existing relationship type so that I can document the kinds of relationships between people associated with the Derrida Library

**Comment by bwhicks** [comment]
As with roles, does the team want a semi-controlled vocabulary for this as part of an initial database?

**Comment by kac3** [comment]
As with roles: there will be a set of vocabulary decided upon by the group, but the list has not yet been finalized. Is it possible to move forward and add the terms during data entry?

**Comment by bwhicks** [comment]
Thanks for this. I've responded for both on #18.
