### ISSUE TITLE
Cover image not displaying properly for some books

### ISSUE THREAD

**Issue by kac3** [Princeton-CDH/derrida-django#190]
Cover images are not displaying properly for some books even when cover image is available and labeled as such (i.e., "Front Cover") in Figgy.  

![screen shot 2018-04-02 at 10 42 08 am](https://user-images.githubusercontent.com/26174024/38200585-f384f9b0-3662-11e8-8a02-8d174716ce65.png)

Possible reason: cover was not set as thumbnail in Figgy.

**Comment by rlskoeser** [comment]
@kac3 the logic is set to use the designated thumbnail from the IIIF manifest (which is something that's standard and easily machine readable); we're not keying on labels.  So we need to make sure that the cover images all get designated the way you want them in Figgy.

**Comment by kac3** [comment]
@rlskoeser thanks, that makes perfect sense. I'll go through and make sure the thumbnails are all properly designated in Figgy and close out this issue.
