### ISSUE TITLE
Make footer sides blue so that side nav items are more visible on hompage

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/derrida-django#191]

**Comment by rlskoeser** [comment]
@thatbudakguy this isn't really broken, just not as nice as we'd like.  I'm going to postpone it.

**Comment by xinyil** [comment]
I feel adding background color is a clearer way of communicating that the navigations are an add-on layer on top to other things. Making sides blue feels a little strange.
Refer to Zeplin.

**Comment by thatbudakguy** [comment]
@xinyil to clarify this - I should just revert the navigation to how it looked before? the zeplin design has a huge grey space above the main area. do I need to add that? if so, what's it for?

**Comment by xinyil** [comment]
@thatbudakguy please add the background color for the navigation text. see zeplin for examples.

the grey part is going to be a banner image, and I think @rlskoeser is working on this?

**Comment by thatbudakguy** [comment]
it is indeed the cause. added the padding but only on XL so it doesn't affect underlines in M, S, etc.

**Comment by thatbudakguy** [comment]
actually, adding padding misaligns them again. maybe could do this with border, but I need to forget about it for awhile.

**Comment by thatbudakguy** [comment]
should be resolved now with no large underlines.
