### ISSUE TITLE
Investigate and fix mdl div wrapping body tag

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#192]
Possibly related to this: https://github.com/google/material-design-lite/issues/1549

**Comment by thatbudakguy** [comment]
not sure what this will break...seems to not have had any effect so far. applied the mdl classes to a div just inside body, but left the template tags like `body_attrs` on body itself.

**Comment by rlskoeser** [comment]
WAVE accessibility browser extension can run on and evaluate the page now.  Much better!
