### ISSUE TITLE
Book page - tab 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#193]
![book-tab](https://user-images.githubusercontent.com/17734456/38215730-c284690c-3696-11e8-8c4f-5415731788b7.gif)
- center the text in box
- currently, text position jumps when selected
- text is in the wrong navy color on hover

**Comment by thatbudakguy** [comment]
- text is centered for me in all browsers...could you try it again?
- fixed text jumping.
- fixed hover color.

**Comment by xinyil** [comment]
@thatbudakguy text is not vertically centered, try make line-height 1?

**Comment by thatbudakguy** [comment]
line-height 1 causes it to be uncentered for me & makes it look like your screenshot.

**Comment by xinyil** [comment]
that's so weird! I was looking at this page from 2 different machines

**Comment by thatbudakguy** [comment]
can we close this?
