### ISSUE TITLE
Sorting buttons being cut off

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#194]
in safari, the text in sorting options has been cut off
<img width="563" alt="screen shot 2018-04-02 at 4 58 30 pm" src="https://user-images.githubusercontent.com/17734456/38215981-6552bcec-3697-11e8-9fd3-874f3a25c3b2.png">

**Comment by thatbudakguy** [comment]
I can't see this in any browser, but added some padding that should hopefully give the letters a little breathing space.

**Comment by xinyil** [comment]
only seeing this issue on my Safari Version 11.0.3 (11604.5.6.1.1)
closing now
