### ISSUE TITLE
Search form interactivity

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/derrida-django#196]
- [x] don't submit the form when a checkbox is selected
- [x] only submit fields that have defined values (otherwise querystring is needlessly long)
- [x] overlay the spinner image on the page when search is active?

**Comment by xinyil** [comment]
the issue we talked earlier today has been captured in #170

**Comment by xinyil** [comment]
"only submit fields that have defined values (otherwise querystring is needlessly long)" no wonder why it was so slow before! so much better now! 

Is it easy to retain the scrolling position after page refreshing? it will be really helpful if I can stay where i've been scrolled after the page refresh instead of having to start from the top and go down again.

**Comment by thatbudakguy** [comment]
@xinyil don't think I understand. wouldn't you have to scroll to the top to change a filter anyway?

**Comment by xinyil** [comment]
but you don’t have to scroll back all the way to the banner. also originally the filter is designed to be fixed as you scroll... we might not have time for this at this point.

**Comment by thatbudakguy** [comment]
would the the filters be "sticky"? i.e. when you scroll further down the header stuff goes away, but the filters stay fixed to the top? it seems like a good way to show more content, and theoretically preserving scroll in that situation would be possible. don't think we have time right now though.

**Comment by xinyil** [comment]
Yes filters were designed to be sticky but this function must be overlooked somehow. I'll add it to the wishlist.

Maintaining scroll position between page load and when going back to the previous page is a different question, and I feel it's a fairly common behavior. If it's not easy to incorporate now we can add to wishlist. But it really disturbs the experience especially when you are browsing a list, and wanting to go back to the list from a detail page.

**Comment by thatbudakguy** [comment]
I'll do some digging about how to implement it - there's not a standard way I know of, but I've never really tried it, so worth looking up

**Comment by rlskoeser** [comment]
Adding sticky filters to the wishlist; everything else here is done.
