### ISSUE TITLE
Corner navigation spacing

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/derrida-django#197]
the bottom right nav link isn't aligned with the bottom left one, as per @rlskoeser

**Comment by xinyil** [comment]
<img width="1247" alt="screen shot 2018-04-05 at 11 43 59 am" src="https://user-images.githubusercontent.com/17734456/38376544-c5b901be-38c6-11e8-80d8-37806274f457.png">
 they still don't. but I think this issue could be of low priority for now.

**Comment by thatbudakguy** [comment]
broken because of my solution to #191

**Comment by thatbudakguy** [comment]
think I've more or less aligned them now.
