### ISSUE TITLE
Keyword search issues

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/derrida-django#198]
- [x] search box should persist, with the search terms visible in it, after the search executes
- [x] line underneath search box is broken, as per @bwhicks 
- [x] default options (i.e. sort) should be selected even if there is a search term specified

**Comment by rlskoeser** [comment]
@thatbudakguy I checked, the generic search form logic is being initialized correctly and has the keyword value available when there is an active search.  The template code is in the `search-bar.html` component template, but I don't see anything suspicious. We're using [django-widget-tweaks](https://pypi.python.org/pypi/django-widget-tweaks) to render the form field and add a class, but that shouldn't cause a problem...  Looking at the source I think the value is actually set, so it must be something in the material design or javascript.

**Comment by thatbudakguy** [comment]
@rlskoeser you bet it was...stared at it so long and it was right in front of me. first line in `site.js`:
```js
$('.mdl-textfield__input').val('')
```
edited that to exclude the header and that let the header persist too, since its value wasn't getting wiped every page load.

broken underline should be fixed, but who knows. fortunately the underline under the magnifying glass isn't even in spec, so I got rid of that part.
