### ISSUE TITLE
Book - layout of related books is broken

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#199]
<img width="1256" alt="screen shot 2018-04-06 at 11 49 55 am" src="https://user-images.githubusercontent.com/17734456/38430930-b797c8de-3990-11e8-93bf-c10cc9331e8a.png">

**Comment by thatbudakguy** [comment]
@xinyil thanks for catching this! the layout for the references tab was *also* broken for me, so I realigned both using css grid. references tab should match spec, and bibliography tab is as close as I could get for now.
![screen shot 2018-04-09 at 10 46 04 am](https://user-images.githubusercontent.com/4924494/38504656-3c22cb72-3be3-11e8-8f0c-94bc1f73a2fc.png)
