### ISSUE TITLE
Add language codes

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/derrida-django#201]
- [x] Whole page
- [x] investigate where we have language information we can provide
- [x] Specific parts, where language is known

**Comment by rlskoeser** [comment]
- revised `Language` model to add codes (we should always do this going forward)
- added method on `Instance` to determine primary language
- added primary language code to book title in book template for book detail pages (assumes book title is in the primary language); I don't think it's worth the effort right nowto add to solr and include in library pages and book titles elsewhere throughout the site
- added language code `fr` to reference anchor text (all references from _DG_ so assuming all French)
- add intervention language codes (annotation text and anchor text) to solr indexes and use them in the intervention templates

**Comment by bwhicks** [comment]
Verified code works as expected and language codes are in all the places that we expect. Solr reindex went off without a problem on the new schema.
