### ISSUE TITLE
Add OCR text to annotated page view

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/derrida-django#202]
- [x] update djiffy to pull OCR text from manifest
- [x] add OCR text to view

# Testing notes
Only one test manifest has OCR updated, which is linked [here](https://test-derrida.cdh.princeton.edu/library/peirce-the-philosophical-writings-of-peirce-1955/gallery/p-93/).
The `alt` text contains the entire page transcription.

If you want to verify that there is `alt` text on the image when there is no OCR text, either click the `inside front cover` or any other manifest's canvas.

**Comment by rlskoeser** [comment]
Was able to see alt text in the html and tested with screen reader and was able to hear the text.  Also saw items without ocr text display a message that text is not available.
