### ISSUE TITLE
Annotation viewer issues

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#208]
- [ ] screen reader navigation aids to help users find annotations buttons (and aria description)?
- [ ] make zone divs `<button>` (`role="button"` seems not to help with tab finding in all browsers and button is best practice anyway. See here on [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role))

**Comment by rlskoeser** [comment]
Duplicate of #204
