### ISSUE TITLE
zotero import: books

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#21]
As a record editor, I want a one-time import of Books from Zotero data into the system so that I can refine and augment the initial data that’s already been collected.

**Comment by bwhicks** [comment]
Quick question about the tags on this import:

I've hit a few that are causing snags because they don't quite fit the schema as I understand it:

```
['dg12aR62pU', 'dg12aR171pU', 'dg12dR38N', 'dg12eR43Y', 'dg12fR50sy', 'dg35bR50pY', 'dg373df___', 'dg373df___', 'dg83cR13sU', 'dg91bR222-224Y', 'dg180bf264pY', 'dg7bRU', 'dg77aR117pY', 'dg108aRU', 'dg64aR101pY', 'dg7cRU', 'dg29c51pY', 'dg373df___', 'dg373df___', 'dg50cR(275a)165pN', 'dg70ab(277e)170pN', 'dg413b225Y', 'dg54iR295pU', 'dg50cR(275a)88pY', 'dg70ab(277e)93pY', 'dg50cR(275a)287pY', 'dg70ab(277e)292pY', 'dg133aR508c137-138Y']
```

The issues:
1) I know reference types for C,Q,E,F. R isn't in the list, so I'll need to know how to handle it.
2) Sometimes a reference type isn't listed, (i.e. `dg70ab(277e)170pN`). Does that mean it's not known/uncategorized/etc or just missing?

This is roughly the only thing that's preventing me from giving you usable data to test the interface on some of which I can have to you in any case (for basic functionality and login). Jean and I have met to handle fields and data models for issue #2 plus your addenda on the dates.

**Comment by kac3** [comment]
Hi Ben, sorry for these snags.  Here are my best efforts to clear things up:

It appears that there was some inconsistency in how different team members tagged reference types.  If my memory serves, we initially developed a system with types Q,E,F,R, in which "R" stood for "reference."  Somewhere along the line, "C" (for citation) got introduced instead of "R," and I'm noticing that this change is reflected in the "Zotero Tag Description" document. The bottom line for the data import is that C and R are actually the same thing: reference type = "reference."  

When a reference type is not listed I assume this is a mistake.  Alex and I can go in and fix these if need be.  Otherwise, it is fine to leave the reference type blank.

Thank you!

**Comment by bwhicks** [comment]
@kac3 Thank you for this. I'll have the import pull them in set it Rs to Cs.

As for the blank items, I'd suggest you and Alex fill them in from the list above for the production import, but for now I'll create a type for 'Unset' and have the import script import them and flag them as such.

**Comment by bwhicks** [comment]
A followup on this, the latest import script (which still needs tweaks tripped over the following):

The Iliade error is an oddity, the other two are types I'm not sure how to handle in the current schema depending on what you want to do with them.  There are some duplications from multiple runs you can disregard for author/editor/translator.
```
Error: Notes - 'document'
Error: Iliade - 'grb grc' is not a valid language tag!
Error:  - 'thesis'
Import either created or found:
        202 books
        78 places
        224 people
        85 publishers
        1107 references from tags

        3 errors
I found 6 references with Unset tags.
They were:
    De la grammatologie, d: Émile ou de l'éducation, None, Unset
    De la grammatologie, d: Tristes Tropiques, None, Unset
    De la grammatologie, d: Profession de foi du, None, Unset
    De la grammatologie, d: Émile ou de l'éducation, None, Unset
    De la grammatologie, d: Phèdre, None, Unset
    De la grammatologie, d: Lettre à M. D'Alembert, None, Unset
```
It also has some duplicates from multiple runs.

**Comment by kac3** [comment]
These errors are very curious.  I searched Zotero for "document" and "thesis" and didn't come up with anything.  Do you know what fields these are coming from?

I'd also be grateful for your insight on what would make a tag "Unset."  I've gone through and tried to clean up tags on those titles, but am not quite sure what I'm looking for (i.e., the reason a tag would be "unset").

Apologies for my novice confusion.  Eager to help fix these issues!

**Comment by bwhicks** [comment]
Hi @kac3, those are tags that I used to grab anything that didn't have a reference type set. So Unset tags were missing the Q/R/C/F/E codes that said what type of reference they were. I used them so that those references could at least be imported.

As for thesis, it may be a dud reference but the Zotero ID is DD32PCDQ.

The document is a set of notes that it looks like you and Alex may have been unsure about. Zotero ID 6I3IZJAH.

**Comment by kac3** [comment]
Thanks @bwhicks !  With the two Zotero ID's I was able to go in and fix those items (actually, I just deleted them since it turns out they were replicated elsewhere).

Working on the unset tags now.

**Comment by kac3** [comment]
@bwhicks I think I managed to find and fix the six offenders among the tags, but please let me know if they are still giving you trouble.  

Glad to hear our data is behaving relatively well!

**Comment by bwhicks** [comment]
@kac3 Great! I'll pull in a new data load tomorrow morning which should get duplicates and a few other minor tweaks that I noted in the import script.

**Comment by bwhicks** [comment]
@kac3 New data is loaded with a fresh database and it looks good. No tags showed up as problematic. Dates are also working properly now. I'll be adding further unit testing to verify as much of this as possible automatically with any future changes, but it is open for your testing again.

**Comment by kac3** [comment]
Hi @bwhicks, ready to close this one!  

I would do it myself, but even after reading your instructions and Github help carefully, I'm still flummoxed.  Maybe there is a setting on my account that needs to be changed?  I don't see the gear icon next to "Issues," and don't see "New Label" or "Edit" anywhere on the label page.

![screen shot 2017-03-22 at 2 45 35 pm](https://cloud.githubusercontent.com/assets/26174024/24215341/da3287ce-0f0e-11e7-8651-3a4c909f0b0f.png)

![screen shot 2017-03-22 at 2 47 28 pm](https://cloud.githubusercontent.com/assets/26174024/24215347/dce7dfdc-0f0e-11e7-955b-3bcc37875264.png)

**Comment by bwhicks** [comment]
Hi @kac3. No problem. I think I can resolve this pretty quickly for you. The first problem was a permissions snag I saw in your screenshots on my end. You should now be able to see some tools that weren't there before. 

There are two ways to close an issue: from its detail page (i.e. this one) or by selected a group of them.

The gear in reference is from the issue page.

<img width="1427" alt="screen shot 2017-03-22 at 2 56 34 pm" src="https://cloud.githubusercontent.com/assets/17815297/24215795/3e9641aa-0f10-11e7-9221-3fd2880f450d.png">

If you click the gear by issues you'll get this window where you can just click an issue to add/remove it.

<img width="591" alt="screen shot 2017-03-22 at 2 58 14 pm" src="https://cloud.githubusercontent.com/assets/17815297/24215801/49fa3f88-0f10-11e7-8fbd-a9cc0a3b3fe3.png">

On the list, you select the issue using a check mark (that should have now appeared) and then click the label box, which I've highlighted and do the same thing for all issues.:

<img width="1084" alt="screen shot 2017-03-22 at 2 58 45 pm" src="https://cloud.githubusercontent.com/assets/17815297/24215888/a1811ccc-0f10-11e7-8a1e-08231ed203e8.png">

Sorry for the confusion! I could have sworn I added your user group to the repo.

**Comment by kac3** [comment]
Thanks so much @bwhicks ! Everything is crystal clear now.  Closing this issue!
