### ISSUE TITLE
configure xml sitemaps 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#211]
We currently have a sitemap but it's only including mezzanine content and don't include last modified dates (which we have for at least some content).  This is important for search engines to be able to find and index site content, and can also help with load on the site so that search engines go directly to content rather than browsing through the site.

Sitemaps are easy to generate with django: https://docs.djangoproject.com/en/1.11/ref/contrib/sitemaps/

We may want multiple, grouped sitemaps by type of content.

Top-level sitemap should be linked in robots.txt file with full url.

**Comment by rlskoeser** [comment]
Added basic sitemaps, no unit tests.  
- base sitemap url should be in robots.txt
- base sitemap should include section sitemaps for each of the main kinds of functionality that's publicly accessible
- sitemap-pages should include modification dates for mezzanine content but not dynamic pages; should include priority based on menu (main menu = higher priority)

**Comment by bwhicks** [comment]
Site maps are present and include all of the priority settings as expected.
