### ISSUE TITLE
Togging checkboxes on the search filters doesn't trigger a form submission

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#212]
## testing notes
- when you initially visit the library page, the "extant in derrida's library" toggle should default to being on
- when you initially visit the references page, the "extant in derrida's library" toggle should default to being off (**is this intentional?**)
- when you toggle a toggle (ha) it should submit the search form
- the form should remember your choices; toggles shouldn't reset on a page reload

**Comment by rlskoeser** [comment]
On the library page:
- extant toggle is on by default, 74 results total
- toggling the extant toggle submits the form, now there are 163 results
- toggling the containing annotations toggle submits the form, now there are 61 results
- reloading the page preserved toggle status

On the reference list:
- all toggles are off when I first load the page
- toggling any of them submits the form and I get a different number of rerefences
- reloading the page preserves toggle state

**Comment by rlskoeser** [comment]
FYI @thatbudakguy yes, the difference in extant toggles is intentional: for the library page, we want to direct people's attention to the books that are extant but provide access to all of them; for the reference page, we want people to see all documented references by default.

**Comment by rlskoeser** [comment]
Just discovered that toggling the checkbox resubmits the form but loses a keyword search term.

**Comment by rlskoeser** [comment]
Ran WAVE browser plugin on both versions of the histogram visualization and it no longer reports any duplicate ids.

**Comment by thatbudakguy** [comment]
Toggling checkboxes doesn't erase the keyword query for me, so this looks good.
