### ISSUE TITLE
Content page style

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#213]
content pages like “how to cite” and “contact” should follow the conventions of the individual blog page, so the text box won’t be too wide

<img width="1238" alt="screen shot 2018-05-04 at 12 27 47 pm" src="https://user-images.githubusercontent.com/17734456/39639205-9779d7ba-4f96-11e8-9eee-2fafb03c6593.png">

**Comment by rlskoeser** [comment]
Updated the template so content pages will get Outwork page styles.
