### ISSUE TITLE
bug generating outwork slug 

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#217]
If you create a new outwork content page as a child of the top-level outwork page, you get `outwork` duplicated in the slug, e.g. `outwork/2018/outwork/test-outwork` - the custom `get_slug` logic should take that into account and handle properly.

**Comment by jabauer** [comment]
When I added 2 new outwork files, they had clean URLS
https://test-derrida.cdh.princeton.edu/outwork/2018/draft-database-statement/
https://test-derrida.cdh.princeton.edu/outwork/2018/draft-data-story/
