### ISSUE TITLE
at certain widths, annotation panel obscures page image

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#225]
Not sure how to address it, but we ought to be able to do something.

<img width="1162" alt="screen shot 2018-09-20 at 5 18 39 pm" src="https://user-images.githubusercontent.com/691231/45847540-601a1200-bcf9-11e8-9986-acbc642dfe6a.png">

**Comment by thatbudakguy** [comment]
Can't get the overlap to happen anymore; looks good.
