### ISSUE TITLE
annotated page view - mobile display

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#226]
The annotated page view isn't very mobile friendly. It was never designed for mobile, and it was a lower priority, but it seems like a some minor tweaks would go a long way:
- ~sidebar nav should be shortened (possibly make it collapsible?)~
- [x] page image should be centered and resized to width
- [x] annotation list should flow below the page image
- [x] book image gallery heading should be centered
- [x] annotation / zoom toggle should be centered

**Comment by rlskoeser** [comment]
See a sample [readux exported page](http://rlskoeser.github.io/osh/pages/front-1/#44d36fda-5e7e-4605-adf1-bfcd8cafb96e) for what I'm thinking of.

**Comment by thatbudakguy** [comment]
This looks great!
