### ISSUE TITLE
Can't edit or create mezzanine or outwork pages

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#227]
Seems to be a javascript/jquery error - see https://github.com/stephenmcd/mezzanine/issues/1289 for an example of the same error (dated solution but probably something similar)

**Comment by jabauer** [comment]
I was just now able to create 2 out work pages including uploading images.
https://test-derrida.cdh.princeton.edu/outwork/2018/draft-data-story/
https://test-derrida.cdh.princeton.edu/outwork/2018/draft-database-statement/
