### ISSUE TITLE
Duplicate ids on the visualization pages

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#229]
Validation error report includes them. See https://validator.w3.org/nu/?doc=https%3A%2F%2Fderridas-margins.princeton.edu%2Freferences%2Fhistogram%2Fde-la-grammatologie%2F and https://validator.w3.org/nu/?useragent=Validator.nu%2FLV+http%3A%2F%2Fvalidator.w3.org%2Fservices&acceptlanguage=&doc=https%3A%2F%2Fderridas-margins.princeton.edu%2Freferences%2Fhistogram%2F

**Comment by thatbudakguy** [comment]
This seems to be caused by two inclusions of the same reference, since the `id` attribute is being generated by the reference id: https://github.com/Princeton-CDH/derrida-django/blob/190d175129f8845fc1eaf267bec5defe19b0d848/templates/components/visualization-marker.html#L6

**Comment by rlskoeser** [comment]
Ran WAVE on both versions of the histogram visualization and it no longer reports duplicate ids.
