### ISSUE TITLE
As an admin, I want to generate a data download for references by derrida work so that I can deposit and version the data for others to use.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#231]
## Notes for development
- custom manage command
- generate both CSV and JSON
- if it's not too difficult, consider generating a frictionless data "data package" to document the fields - [datapackage-py](https://github.com/frictionlessdata/datapackage-py) looks possible
- export should use consistent identifiers (URIs) across all datasets for references to books and annotations

**Comment by jabauer** [comment]
Data package dropped for release 1.2

**Comment by jabauer** [comment]
I have reviewed the references data download and it includes all the data required.
