### ISSUE TITLE
As an admin, I want to generate a data download for annotations so that I can deposit and version the data for others to use.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#232]
## Notes for development
- custom manage command
- generate both CSV and JSON
- should include: book title, page label, tags, text, text language, text translation, quote, quote language, author (annotator)
- if it's not too difficult, consider generating a frictionless data "data package" to document the fields - [datapackage-py](https://github.com/frictionlessdata/datapackage-py) looks possible
- export should use consistent identifiers (URIs) across all datasets for references to books and references
- export should not include images because of the possible legal concerns; we should document that images are only available through the project site

**Comment by jabauer** [comment]
Data package dropped for Release 1.2

**Comment by jabauer** [comment]
I have reviewed the annotations download and it has all the data noted above.
