### ISSUE TITLE
Invalid searches cause unhandled exceptions 500

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#240]
Invalid searches cause an exception because they return no results (as revealed by someone trying an SQL injection.

```
1.11.16
AttributeError
'NoneType' object has no attribute 'items'
/var/www/derridas-margins/derrida/interventions/forms.py in set_choices_from_facets, line 68
```

**Comment by rlskoeser** [comment]
I couldn't figure out a way to trigger this from the interface, so I don't think this is testable. I'm pretty sure I've fixed the part of the code that could trigger the exception, so I'm going to go ahead and close. We can always re-open if we discover it's still not fixed.
