### ISSUE TITLE
Figgy connection errors are uncaught in CanvasDetail view

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#241]
When getting a IIIF url at `derrida/books/views/py` l. `607`, the error raised is not the Python builtin `ConnectionError`, but `requests` `ConnectionError` (which inherits from `IOError`).

The error handling should correctly grab the `requests` error.

**Comment by rlskoeser** [comment]
Should be fixed by catching the correct exception. Will re-open if we keep seeing error emails for this after deploying 1.2.2
