### ISSUE TITLE
Reference card on the visualizations should include reference type

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#243]
## Notes for testing
Go to either of the visualizations and look at the reference card shown on popup. It should include a label at the top indicating the specific kind of reference it is.

---
This means if you want to browse references in order in the chapter by chapter view, you can't see whether something is a footnote, quotation, etc.

**Comment by rlskoeser** [comment]
I checked zeplin, these were included in the design - not sure why they were suppressed.

**Comment by thatbudakguy** [comment]
looks good - the reference type pill shows up and is clickable for all references.
