### ISSUE TITLE
switch to node-sass and use local autoprefixer/postcss

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/derrida-django#250]
this requires whatever setup is needed to run node/npm for derrida deploys, which isn't configured yet. we just need to make sure that `npm ci` can run. after that, we need to revert commits
https://github.com/Princeton-CDH/derrida-django/commit/7c43ce865ab6e153c4fe2fc18943e6ff4d261399 and https://github.com/Princeton-CDH/derrida-django/commit/fdf68b2acf96557232dda7ee40a111a9348262d8.

**Comment by rlskoeser** [comment]
Adding the `build_npm` role wasn't sufficient to fix the deploy errors; perhaps we need some other configurations to tell the build what version of npm to use.

**Comment by kmcelwee** [comment]
* Travis is not being used anymore
* @rlskoeser decided that messing with this as we're trying to archive isn't smart
* I've added documentation to `settings.py.sample` so that this is easy to fix when necessary
