### ISSUE TITLE
If cached iiif image urls change, images on the site will be broken

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#253]
**Describe the bug**
When PUL migrated to a new IIIF image server a few months ago, all the book asset images served by PUL on the site broke.

**Additional context**

The cached manifests can be updated by running the import script with the update flag set:
```
python manage.py import_digitaleds --update PUL
```

Running this update resolved the majority of problems, but some cover images are still broken. Brief investigation indicated that the iiif versions of the images are working correctly, but the named images (like thumbnail) are not. Possibly there's some error in the logic for sizing that is triggered by some images and not others.

To fix the immediate problem
- figure out why some images are not rendering and fix the problem (code? manifest updates? something else?)

Longer term:
- Consider setting up site crawling that would flag image 404s over some threshold so we're alerted if this happens in future
- Consider running the import / update periodically (monthly? quarterly?) to make sure cached manifests are reasonably fresh

**Comment by kmcelwee** [comment]
@rlskoeser Please confirm that this is an example of the problem you're describing https://derridas-margins.princeton.edu/library/aristotle-organon-categories-de-linterpretation-1959/gallery/

**Comment by rlskoeser** [comment]
@kmcelwee I was thinking of the missing covers on the library page https://derridas-margins.princeton.edu/library/ but the example you linked is likely the same problem.

**Comment by kmcelwee** [comment]
When deployed, iiif links were no longer broken in the library search results page, e.g.:
https://test-derrida.cdh.princeton.edu/library/aristotle-organon-categories-de-linterpretation-1959/
