### ISSUE TITLE
Disable search filters

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/derrida-django#268]
Use CSS to disable things that are no longer functional: 
```css
cursor: not-allowed;
pointer-events: none;
```

Let's keep the drop-downs functional but disable the inputs and the clear selection.

Should be fine to disable form labels and inputs pretty broadly without worrying about filtering too specifically.

- [x] Grey out or lower opacity on form fields — suggest using opacity or rgba/lighter gray color if we want to limit to text (we don't want the drop-down backgrounds to be partially transparent so text may be easier)
- [x] Disable all form inputs (possible exception: search within author filter could be kept active)
- [x] Disable site search bar
- ~Remove clear all~ (no need to remove this, it links to the search with no filters and works correctly)
- [x] Disable "clear selection" on filter drop-downs
- [x] Disable non-default sort options
- ~Deactivate author and reference type links in search results~ (no need to disable, these have been archived)

**Comment by rlskoeser** [comment]
completed in https://github.com/Princeton-CDH/derridas-margins-archive/pull/6
