### ISSUE TITLE
customize nginx site for wayback deploy

### ISSUE THREAD

**Issue by kmcelwee** [Princeton-CDH/derrida-django#287]
nginx configurations needed:
- [x] determine if we can use wayback in proxy mode within nginx
- [x] map 404 to archived 404 page in the archive crawl `/404/` 
- [x] map 50* to archived 500 page in the archive crawl `/_500/` (retain actual error code if possible)
- [x] disable iiif image urls
- ~proxy iiif images using generated map list~
   - ~update ansible passenger role to copy supporting files for use in nginx config~
- [x] use static version of sitemedia to override wayback content (for speed/efficiency)
   - [x] capture output from `collectstatic` in production and add to archive repo
- [x] local static copy of sitemaps so we can override/customize modification time/frequency
   - [x] #291 
- [x] fix banner styles/overlap for image viewer so deep zoom button is clickable

**Comment by rlskoeser** [comment]
- wayback should run on a separate port and be configured in a second nginx conf
- main nginx conf should use `proxy_pass` to wayback on 8080
- all customization (404s, static content, etc) should be in the outer nginx conf
- use a maintenance location for 404/500
