### ISSUE TITLE
interventions: pen color if ink used

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#29]
As an intervention data editor, I want to be able to add and edit the color if the ink type is “pen," so that I can see if there are patterns in Derrida's pen usage and whether he revisited the same text.

**Comment by bwhicks** [comment]
@kac3 Is my assessment of the why ("so that...") correct for the user story, more or less?

**Comment by kac3** [comment]
Sorry for not making this explicit myself!  Yes, that is one reason.  The other reason is "so that I can see how many times Derrida revisited a given text" (since different pen colors would be indicative of readings at different times).

**Comment by bwhicks** [comment]
Great, I've adjusted the user story accordingly.

**Comment by rlskoeser** [comment]
Implement using tag functionality from #39.  Recommend using tags like "blue ink", "black ink", etc. to make the tag meaning clear.

**Comment by rlskoeser** [comment]
I added a couple of initial tags for testing purposes, but the project team should add more and edit as needed.

**Comment by kac3** [comment]
@rlskoeser Agree with your recommendation to use tags like "blue ink," "black ink," etc.
