### ISSUE TITLE
interventions: select verbal intervention

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#31]
As an intervention data editor, I want to select verbal interventions on a page image and enter a transcription of the text so I can document the intervention and where it occurs.

Including initial annotation implementation part of this user story.

- [x] enable django-annotator-store 
- [x] create interventions app with custom annotation model
- [x] add link to digital editions from admin (as in winthrop)
- [x] customize djiffy templates and enable annotator.js

**Comment by rlskoeser** [comment]
I was confused by the wording on this one, somehow - but reading it now I see, this is just the basic first-pass image selection annotation functionality.

**Comment by rlskoeser** [comment]
Basically the same as #30 with the addition of text transcription for the annotation.

**Comment by kac3** [comment]
Hi @rlskoeser, a very basic question: if I enter text in the text field, will an annotation automatically count as "verbal"?  I ask because this is one of our key annotation filters.  If that does not happen automatically, should we create a "verbal annotation" tag?

**Comment by rlskoeser** [comment]
@kac3 we can easily distinguish verbal/non-verbal based on the presence of text in the text field.  Would it be helpful to add a verbal/non-verbal indicator to the admin view like I did with the "is_digitized" ?

**Comment by kac3** [comment]
@rlskoeser It would be *very* helpful to have an "is digitized" indicator in the admin view. Thank you!
