### ISSUE TITLE
interventions: flag annotation transcription as uncertain

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#32]
As an intervention data editor, I would like to be able to tag part or all of transcribed verbal intervention text as “uncertain.”

**Comment by rlskoeser** [comment]
Implement using tag functionality from #39 . Recommend tagging as "transcription uncertain" or something similar so it is clear to everyone what portion of the intervention is uncertain.

**Comment by kac3** [comment]
@rlskoeser This tagging recommendation makes sense to me.
