### ISSUE TITLE
interventions: tag annotation text as illegible

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#33]
As an intervention data editor, I would like to be able to tag a verbal intervention as “illegible” so that I can clearly indicate when the text is unreadable.

**Comment by rlskoeser** [comment]
Implement using tag functionality from #39

**Comment by bwhicks** [comment]
@rlskoeser On this one, we can certainly tag an entire annotation as illegible. Does the use case imply being able to tag specific text?

**Comment by rlskoeser** [comment]
@bwhicks thanks for pointing that out. The user story as written does indicate tagging part of the text as illegible, but I can't think of a simple way to do that.  Katie already agreed to using a tag for this, so I say we revise the story and declare indicating a specific part of the text as illegible to be out of scope.

**Comment by bwhicks** [comment]
@rlskoeser Agreed and so changed to express that we're tagging the annotation.

**Comment by rlskoeser** [comment]
@bwhicks thanks for making the update.  It did occur to me, the team could always add another tag, e.g. "partially illegible", if they want to differentiate.

**Comment by kac3** [comment]
@rlskoeser Thanks for the "partially illegible" suggestion. That's a good solution to this issue.
