### ISSUE TITLE
interventions: able to leave all fields empty

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#35]
As an intervention data editor, I want the option of leaving all fields blank so that I can accurately describe non-verbal interventions or interventions that don't relate to anchor text.

**Comment by bwhicks** [comment]
I think we get this for free with marganlia + annotator.js, but noting it anyway.

**Comment by rlskoeser** [comment]
Leaving this open as a reminder to make sure we don't accidentally require something that should be optional.

**Comment by rlskoeser** [comment]
Confirmed this is working now that we've added all the fields.  Works on a new annotation, and also every field can be cleared out once set.
