### ISSUE TITLE
interventions: add a tag describing annotation from a set list

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#39]
As an intervention data editor, I want to tag interventions from a pre-defined list so that I can describe the characteristics and type of intervention.

Previous version of the story that includes preliminary tag list:
> As an intervention data editor looking to add a tag describing a particular intervention, I would like to be able to choose from an auto-complete (or similar) menu of previously established tags: underlining; circling; arrow; bracket(s); line; correction; marginal mark; punctuation mark; verbal annotation; insertion; flyleaf note.

- [x] create new intervention tag model
- [x] fixture + migration for initial tags to include
- [x] configure annotator to include tag field with autocomplete lookup

**Comment by bwhicks** [comment]
Can use annotation code from https://github.com/Princeton-CDH/winthrop-django/issues/43 (use case looks entirely similar), except for annotation vs insertion (which will need to be categorical and chosen up front per conversation with @rlskoeser).

**Comment by kac3** [comment]
@rlskoeser @bwhicks This works, but it's a little wonky. I find that when I try to select a highlighted tag (either from the dropdown menu or after typing it), it usually takes a few tries to get it to actually select.  This might just be my browser (Safari), but it's happening consistently.
![screen shot 2017-07-18 at 11 57 41 am](https://user-images.githubusercontent.com/26174024/28312248-c1b803ee-6bb2-11e7-8c73-3582a348f0e0.png)

**Comment by rlskoeser** [comment]
@bwhicks can you take a look at this, maybe test in a few different browsers and see if the behavior is any different?

**Comment by bwhicks** [comment]
@rlskoeser I can confirm this on Firefox 55.0b8 and Chrome 60.0.3087.0 (Canary). Actually on Chrome, I can't get it to select period.

**Comment by rlskoeser** [comment]
Drat.  I see from the console that I broke something in the javascript.  I'll kick it back for us to fix.
