### ISSUE TITLE
insertions: tag interventions with insertions with their document type

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#45]
As an intervention data editor, I want to be able to add and edit tags to indicate the type of document inserted, for example: post-it note, calendar page, hotel stationery, newspaper article, correspondence, tree leaf, etc. , so that I can catalogue what materials Derrida used in annotating his library.

**Comment by rlskoeser** [comment]
Not in current phase of work; implementation likely to change when/if we revisit later.
