### ISSUE TITLE
insertions: associate with approximate date

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#46]
As an intervention data editor, I want to be able to enter an approximate date for an insertion, for example: 1980s, post-1965, etc., so I can indicate when the team thinks this was added to the book.

**Comment by bwhicks** [comment]
@kac3 I wanted to double check with this one. Do you plan to keep to year ranges or is there likelihood you'd want to mention months or editorialize with comments a bit?

**Comment by kac3** [comment]
@bwhicks Good question. There is definitely the possibility we would want to editorialize, so it would be great if this were a text field.

**Comment by rlskoeser** [comment]
Not in current phase of work; implementation likely to change when/if we revisit later.
