### ISSUE TITLE
footnotes: associate with anything lookup

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#49]
Currently the footnote object lookup does not work with all content types for objects.

**Comment by bwhicks** [comment]
Fix should be similar to fix for https://github.com/Princeton-CDH/winthrop-django/issues/28 (commit https://github.com/Princeton-CDH/winthrop-django/commit/2b15e6beac2a200003fc4731336c24315be01f6b)

**Comment by kac3** [comment]
@bwhicks @rlskoeser Unclear on how to test this (apologies for being slow on the uptake!).

**Comment by rlskoeser** [comment]
My apologies for not documenting better, this one is a little confusing (we ran into a similar problem with the Winthrop team).  

Select footnote from the footnote section in the main admin page, and when you add a footnote you'll see the option to choose what kind of object you want to reference:
<img width="662" alt="screen shot 2017-07-18 at 10 00 01 am" src="https://user-images.githubusercontent.com/691231/28320985-030dad0c-6ba0-11e7-9000-913ddc4a475a.png">

Once you choose a type, you'll get a little search icon that will pull up the admin list view for that item so you can choose one.
<img width="683" alt="screen shot 2017-07-18 at 10 01 38 am" src="https://user-images.githubusercontent.com/691231/28321041-2e13f4b6-6ba0-11e7-9928-2581dc705c00.png">

This interface is mainly for kinds of content that we haven't added footnote editing to the main edit form.  (I just checked, and we have it for work, instance, and person-book.)

**Comment by kac3** [comment]
@rlskoeser I still have a few questions about using the footnote function, but this is working well!
