### ISSUE TITLE
books: view associated interventions

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#5]
As a record editor, when I’m editing a book record I want to see a list of all the interventions (annotations and insertions) associated with that book so that I can review and update interventions by related book.

**Comment by rlskoeser** [comment]
Note that we can't make interventions editable on the book admin edit form because they aren't directly related to book, but we can create a custom template and include a list of them with links to view and edit (perhaps to both views? admin & annotator view).

**Comment by rlskoeser** [comment]
@bwhicks I'd appreciate it if you took a look at the template changes I've made and see if you think it's reasonable/sufficient.  I think the development is done but I'd like to write some unit tests to test the template.

**Comment by bwhicks** [comment]
@rlskoeser I think this looks good, but I am bumping into an issue, which I assume may be my dev environment but I'd like to raise: When viewing an intervention in the edit view of the admin, the view raises: `django.urls.exceptions.NoReverseMatch: Reverse for 'canvas-autocomplete' not found. 'canvas-autocomplete' is not a valid view function or pattern name.`

**Comment by rlskoeser** [comment]
@bwhicks ack, I have uncommitted changes on my local copy of djiffy.  Thanks for catching that!

**Comment by rlskoeser** [comment]
Still to do: update djiffy and add unit test for admin customization
