### ISSUE TITLE
book instances: print date with optional month/year

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#52]
As a record editor, I want to document the print date for a book, including month and year when available, so that I can check if a given copy was available to Derrida when he was writing a text.

More detailed explanation from @kac3 about why the print date granularity is important:

> The print date is pretty important for this project because it allows
> us/users to tell if Derrida would have been able to consult a given copy
> of a work while writing a text.  I know of at least one text in our corpus
> that has a print date in February 1967, which allows us to include it in
> this project because we know Derrida didn't complete De la grammatologie
> until the spring of that year (it was published in the fall).  We can't
> say for sure that he did consult it, but it is possible.  Just having
> "1967" as the print date wouldn't allow us to draw that conclusion with
> the same degree of certainty.  Perhaps day isn't necessary, then, but I
> would like to keep the month if possible.

**Comment by rlskoeser** [comment]
We should check if turning the the Django admin date hierarchy on the print date field looks helpful or meaningful.  Maybe also create a custom property for date display based on known accuracy (i.e. only display year or year month rather than year-01-01 if month and/or day are not known).

**Comment by kac3** [comment]
@rlskoeser A little bug here: even when I de-select all three of the "print date known" boxes, the system is giving me an error if I don't enter any print date.
![screen shot 2017-06-02 at 11 14 26 am](https://cloud.githubusercontent.com/assets/26174024/26719785/329200d4-4786-11e7-8530-c55d2635313b.png)
