### ISSUE TITLE
edit books as works & instances

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#53]
As a record editor, I want to add and edit bibliographic data for works and instances of works so I can document shared metadata and group different copies and editions of the same work.

**Comment by rlskoeser** [comment]
Adding this story to capture the database refactoring to split books out into works and instances as well as the admin UI changes to edit bibliographic data as works and instances.  I'm inclined not to explicitly duplicate/rework the previous version of list and search user stories. The functionality will be adapted from the previous stories, although not exactly the same, and it will need to be tested - so if it's helpful to articulate those stories explicitly we probably should.

**Comment by rlskoeser** [comment]
A few notes for testing:

- the data migration is not intended to be exhaustive in terms of grouping instances into works, but just to do whatever can be reasonably detected from the data in the system; we expect there will be manual clean up required, but tried to take care of what could be easily automated
- the data migration creates minimal work/instance records for volumes that book sections belong to; when it does so, it adds a comment to the notes field, so you should be able to find them by searching for "stub"
- please test search/browse/editing for both works and instances to check that nothing has been missed in this refactor

**Comment by kac3** [comment]
@rlskoeser I'm having a little trouble conceptualizing how the "year" field in the Derrida work maps onto the various date fields for instances.  How were you envisioning this?  Original publication is the date that makes most sense to me, but I want to make sure we're on the same page.

**Comment by kac3** [comment]
@rlskoeser I'm noticing that the automated grouping of instances into works generated some rather strange groupings and missed a bunch of others. I'm thinking it would actually keep things simpler on our end to do all of the instance/work grouping manually.

**Comment by kac3** [comment]
@rlskoeser A little bug with the print date: even when I de-select all three of the "print date known" boxes, the system is giving me an error if I don't enter a print date.
![screen shot 2017-06-02 at 11 14 26 am](https://cloud.githubusercontent.com/assets/26174024/26719730/fb92fafc-4785-11e7-8521-996092a943ee.png)

**Comment by rlskoeser** [comment]
@kac3 thanks for the feedback.  Yes, we're in agreement about the work year - I'll add some help text on the field as a way of documenting that.

Sorry to hear the grouping isn't useful, but understand.  I'm fine with removing that logic, just wanted to confirm - an instance must be tied to a work, so is it fine if I revise to create one work for each instance and then you all can just go in and group them and remove extraneous works?

**Comment by kac3** [comment]
@rlskoeser Confirming that yes, it is perfect if you create one work for each instance and we will do the grouping manually. Thank you!
