### ISSUE TITLE
As a record editor, I want to mark a copy of edition in order to differentiate when two exact copies were in Derrida's library.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#55]
## Notes for testing
Copy letters have been automatically assigned because we needed them to create slugs for urls.   For an examples of where they've been set, go to the work instance list search for "ursprung" or "emile".

**Comment by rlskoeser** [comment]
Optional short text field.  Contents will be e.g. 'A', 'B', 'C', but I don't think we need to validate that.

**Comment by araiffe** [comment]
I see what was done for "Emile" and "Ursprung" and it appears to be working fine.
