### ISSUE TITLE
As a record editor, I want to document page ranges for chapters in Derrida works so that references on the site can be filtered and displayed by chapter.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#56]
## Notes for testing
- This is edited in a new section when you edit the record for a Derrida work.
- Sections without page numbers will be consider headings; add page numbers for chapters only.
- (I have a version of the section data that I entered to demo the site at DH but want to make sure you are comfortable making updates.(

**Comment by rlskoeser** [comment]
@jabauer any suggestions about how to model this in the database?  Xinyi's design for the data visualization shows two levels of hierarchy (sections and chapters), I don't know if we need more than that.

I've been thinking we can either create sections with start and end page numbers and then filter `Reference` based on the `book_page` property _or_ we can create sections and associate references with them directly.  The first approach may only work for numeric page ranges; the second approach will probably require more manual effort.

I'm not sure how to handle the hierarchy.  Any idea if we need it, or what depth we might need?  We could use [django-mptt](https://django-mptt.readthedocs.io/en/latest/) but I'm not sure if that's overkill.

**Comment by jabauer** [comment]
I'm leaning toward the first option (designate ranges and then do a page lookup).  Is there a way to do it by image sequence as well as page number to get around the issue of unnumbered pages?

**Comment by rlskoeser** [comment]
Do you mean, use page ranges where possible but allow project team members to explicitly associate a reference with a section?  (Would there even be a section that doesn't have page numbers?)

What about hierarchy, any thoughts on whether we need that?  Maybe we can just infer hierarchy based on page ranges.

**Comment by rlskoeser** [comment]
@araiffe @kac3  FYI, you can add section headings for display on the visualization page by leaving out page ranges. As an example, here's how I've entered the sections in my dev admin site:
<img width="702" alt="screen shot 2017-10-06 at 10 21 04 am" src="https://user-images.githubusercontent.com/691231/31282294-24705700-aa80-11e7-970a-f18f23a59bf3.png">
And here is how the heading displays on the visualization page:
<img width="523" alt="screen shot 2017-10-06 at 10 21 22 am" src="https://user-images.githubusercontent.com/691231/31282321-370e3bd4-aa80-11e7-8eab-300febe7953e.png">

**Comment by kac3** [comment]
@rlskoeser Fantastic - I think that should take care of it!

I just went to try and fix this, however, and - am I being totally crazy here? - it seems that the "Derrida work section" fields are gone.  Any help would be much appreciated!
![screen shot 2017-10-06 at 10 27 48 am](https://user-images.githubusercontent.com/26174024/31282713-618585ec-aa81-11e7-8d9e-bb43c3f24ade.png)

**Comment by rlskoeser** [comment]
@kac3 please check and make sure you're on the test site!

**Comment by kac3** [comment]
@rlskoeser Ah, the old test site issue!  My apologies!

**Comment by kac3** [comment]
@rlskoeser Separating out the sections definitely clarifies the display!  

Some of the chapter names still look a little choppy, though. I'd be grateful if @xinyil could take a look!

**Comment by rlskoeser** [comment]
@kac3 great, thanks for checking.  I'll ask her to look at it next week.

**Comment by araiffe** [comment]
@kac3 can this be marked as tested and resolved or should we wait for the feedback?

**Comment by rlskoeser** [comment]
@araiffe @kac3 if you're satisfied with the admin interface for entering the chapters and sections, go ahead and close this one.  We'll deal with the display issue on #78 .
