### ISSUE TITLE
books: view indicator and sort instance on digital edition

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#65]
As a record editor, I want to see an indicator if a library instance has a digital edition associated and be able to sort on the presence of a digital edition so that I can easily get to volumes that have been digitized.

This came up as I was working on #7 and I thought it would be pretty valuable to have in the admin interface.  Adding it as a story to ensure it gets tested.

**Comment by kac3** [comment]
@rlskoeser Thank you for adding this!

**Comment by kac3** [comment]
@rlskoeser Realized that I am not able to sort on presence of digital edition. Same goes for all the "Is ..." categories ("Is extant," "Is annotated," etc.).

**Comment by rlskoeser** [comment]
My apologies, this is another thing about the interface we should have told you about.

Any of the headings in the admin list view that are blue can be clicked to sort by that column.  You can click again to toggle sort order, and you can combine sorting on multiple fields.

<img width="1592" alt="screen shot 2017-07-18 at 9 28 58 am" src="https://user-images.githubusercontent.com/691231/28319375-b73e9660-6b9b-11e7-94cd-3b27e62c8702.png">

**Comment by kac3** [comment]
@rlskoeser Thanks for clarifying!  For some reason, though, none of the "Is..." columns are clickable for me (tried in Safari and Chrome).  The other blue columns (Author, Copyright year, Call number) are, however.  Any idea what might be causing this?

**Comment by bwhicks** [comment]
@kac3 It's the 'QA' banner. If it's visible, it's click area gets in the way of the selectors. That shouldn't be an issue on production, and for future user tests, just click 'OK' on the banner and the problem should go away.
