### ISSUE TITLE
books: associate book with image/canvas

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#7]
As a record editor, when I’m editing a book I want to be able to view the associated  digitized materials so I can see pictures of the book, annotations, insertions, and other relevant markings.

- [x] add djiffy to the project
- [x] link derrida library item to djiffy iiif manifest as digitized edition
- [x] make digitized edition visible in instance admin edit form
- [x] update djiffy to support auth token access for restricted IIIF manifests
- [x] extend djiffy default import script to link digitized materials with library item records
- [x] finalize import script based on library inclusion of source metadata identifier
- [x] unit tests for import script

**Comment by rlskoeser** [comment]
Revised the story to reflect the fact that digitized books will be loaded via script and associated with library items.

**Comment by rlskoeser** [comment]
Drat, maybe I edited incorrectly.  @bwhicks how is this different from #27 ?

**Comment by bwhicks** [comment]
@rlskoeser I think the difference is between an inline or similar accomodation in the book admin vs being able to associate the two as a concept.

They're pretty clearly related but this one could be edited to reflect the idea of an inline or explicit admin story?

**Comment by rlskoeser** [comment]
The last item is waiting on this issue being implemented in plum: https://github.com/pulibrary/plum/issues/1372 

Based on the conversation, the implementation will need to be tweaked since the source metadata id will look slightly different than the local identifier we have for winthrop.

**Comment by rlskoeser** [comment]
Sample script output for importing a handful of items:

In your testing, please check that this is sufficient information to manually associate any digitized editions that are not automatically associated.

```
./manage.py  import_digitaleds [manifest uris omitted]
Imported pz890vk14g "House - Gift Books, Works By and About Derrida, and Related Items - Montaigne. Essais."
No matching instance for pz890vk14g (findingaids.princeton.edu/collections/RBD1.1/c7822)
Imported pqr46tp355 "House - Gift Books, Works By and About Derrida, and Related Items - Communications n°4."
. Associated pqr46tp355 with "Rhétorique de l'image (1964)"
Imported phx121388m "House - Gift Books, Works By and About Derrida, and Related Items - Derrida, Jacques. De la grammatologie."
No matching instance for phx121388m (findingaids.princeton.edu/collections/RBD1.1/c8193)
Imported phd76vq33z "House - Living Room and Attic - Annotated or Inscribed - Pensée Formelle et Sciences de l'Homme"
. Associated phd76vq33z with "Pensée formelle et sciences de l'homme (1960)"
Imported pbc389901n "House - Living Room and Attic - Annotated or Inscribed - L'écriture et la psychologie des peuples"
. Found 2 matching instances for findingaids.princeton.edu/collections/RBD1.1/c13577
[manifest uri] has already been imported [repeated]
Imported p3b593z50x "House - Living Room and Attic - Annotated or Inscribed - David, Madeleine. Les Dieux et le Destin en Babylonie"
. Associated p3b593z50x with "Les dieux et le destin en Babylonie (1949)"
Imported pms35x1541 "Studio - Wall 1 - Emile ou l'éducation"
. Found 2 matching instances for findingaids.princeton.edu/collections/RBD1/c10457

URLs processed: 10
Manifests imported: 7
Manifests not matched to library work instances: 4
```

**Comment by rlskoeser** [comment]
We can't import the whole collection until auth token behavior in plum is expanded to work on collection manifests as well as individual items.  https://github.com/pulibrary/plum/issues/1405

**Comment by kac3** [comment]
@rlskoeser I see one incorrect association here, but it looks like it's due to a metadata error in plum. I can correct it manually.

Imported pqr46tp355 "House - Gift Books, Works By and About Derrida, and Related Items - Communications n°4."
. Associated pqr46tp355 with "Rhétorique de l'image (1964)"

**Comment by rlskoeser** [comment]
Are you sure that's an error?  The plum record has the source metadata identifier **RBD1.1_c478** which corresponds to the finding aid URL we have for that item: http://findingaids.princeton.edu/collections/RBD1.1/c478 

I do see that the item is a journal article from _Communications_, and I wonder if that's causing confusion. Would it be helpful to include more information so you can more easily check how items are matching up?  e.g., we could include journal name or book name for book sections.

**Comment by kac3** [comment]
@rlskoeser It's suer weird, but it's definitely an error (on plum).  The images are actually of this item:

https://findingaids.princeton.edu/collections/RBD1/c13186

**Comment by rlskoeser** [comment]
@kac3 oh! very weird.  We should tell them about that and any other errors we see so they can fix it!   I think we need get any errors like that fixed before your team starts entering interventions.

**Comment by kac3** [comment]
@rlskoeser Glad we caught this one! I went back and checked, and it looks like the images for these two items (c13186 and c478) are switched. The error is also in the original image browser, not just plum. 

I'll go through all the other items during testing this week to make sure there aren't any other errors of this kind!

**Comment by rlskoeser** [comment]
@kac3 I'm very glad you caught it too!  Roel was just asking me the other day if the digitization was all good from our end, so this is good timing.
