### ISSUE TITLE
As a user, I want to view a paginated list of books in Derrida's library that are cited in Derrida's works so that I can engage with the materials he referenced in his writing.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#71]
## Notes for testing
For this story, just check the basic list, pagination, and display handling.  Filtering and sorting is tested elsewhere.

---

Should display thumbnail, title, author, year, and copy of edition (see #55).  Default sort is by author.

List should be paginated.  Use query strings for pagination. 16 volumes per page based on the design.

**Comment by bwhicks** [comment]
Proposed slug from @rlskoeser @bhicks meeting: 

slugified-title-year-identifier-from- #55, 
Truncate on period, colon, comma in title? Distinguish on author?
Editable with 301 edit

**Comment by rlskoeser** [comment]
This story is for basic library item display with pagination.  We'll write additional user stories to implement and test sorting and filtering options separately.

**Comment by araiffe** [comment]
I tested the visualization and it works as described.
