### ISSUE TITLE
As a user, I want to view a paginated list of references in Derrida's works so that I can see the extent and range of references he made to materials in his library.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#73]
## Notes for testing
Update 10/9 - removed page location letter from reference display throughout the site.

***

Should display reference type, page thumbnail; referenced work title, author, date, pages; text of citation, page in Derrida work.

Default sort order is by page order in Derrida work.

Pagination: 16 items per page.

**Comment by bwhicks** [comment]
Slug format: dg100a (abbreviation, derrida work page number, and page loc)
Returns: HTML snippet

**Comment by araiffe** [comment]
@rlskoeser After discussing with @kac3, we have a question regarding this is it possible to remove the a/b/c/d… after the page number?

**Comment by rlskoeser** [comment]
@araiffe yes, that's easy to do.  We'll drop it from the display.
