### ISSUE TITLE
Navigation L M S

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#76]
@kevinglover  please refer to zeplin for the numbers

- incorrect rollover and active status for SML
- align logo with the text, align search button with the text
- move navigation to corners

<img width="1440" alt="screen shot 2017-07-26 at 4 48 56 pm" src="https://user-images.githubusercontent.com/17734456/28643156-e7bfc966-7222-11e7-961a-6d947a75c3a5.png">

**Comment by xinyil** [comment]
<img width="780" alt="screen shot 2017-08-17 at 4 27 27 pm" src="https://user-images.githubusercontent.com/17734456/29432278-fda5ad16-8368-11e7-859e-166b1ec1ee6f.png">
M nav is exceeding the text 


incorrect S nav behavior: 
<img width="524" alt="screen shot 2017-08-17 at 4 26 37 pm" src="https://user-images.githubusercontent.com/17734456/29432292-10d8ff78-8369-11e7-8297-be5efa98b121.png">

**Comment by xinyil** [comment]
Navigation in L is 20 px = 1.25 em

**Comment by xinyil** [comment]
- I would recommend remove the animation of rollover because it does't create meaning. If we'd like to keep animation, the style that will make sense is letting the line appear from left to right like it's been underling.

- Navigation in L is 20 px = 1.25 em

- underline should not exceed the width of the text

- in M, menus are displayed in incorrect sequence. it should be Library, reference, viz, outwork

- nav in S has not been fixed. please refer Zeplin to see the expanded view in S

**Comment by kevinglover** [comment]
@xinyil

The nav S should be full width in develop now.
<img width="484" alt="screen shot 2017-10-11 at 1 57 30 pm" src="https://user-images.githubusercontent.com/2983582/31457885-3767d5d0-ae8c-11e7-8535-c794dcf0c27c.png">



The rollover state is meant to give feedback that the link is clickable for usability. I added the animation for the hover in the feature/solr-range-facet branch. I also rearranged the navigation and set the corner nav font-size to 20px.

![underline-animation](https://user-images.githubusercontent.com/2983582/31459001-c6568e1e-ae8f-11e7-879c-2f7ded09c79f.gif)
![underline-animation-2](https://user-images.githubusercontent.com/2983582/31459005-c98dff4a-ae8f-11e7-83ed-e4ff52fcc236.gif)

**Comment by xinyil** [comment]
The underlining animation looks great! Is the line farther away from the text in M than in L?

nav in S has not been fixed. The menu expands at the top and you should be able to see the rest of the page beneath that.

**Comment by kevinglover** [comment]
@xinyil The underline in M and L are the same absolute distance away, but it might look different because the font size is larger in L than in M.

The small nav pulling down from the top will require some larger changes. Originally, I didn't understand that it was to pull down from the top based on the specs in zeplin. I must have missed the note. 

Can we make the S menu a separate card?

**Comment by xinyil** [comment]
We should move it closer for smaller type so it looks visually the same.

What do you mean by making it a separate card?

**Comment by kevinglover** [comment]
@xinyil I mean opening up a issue dedicated to the small menu, so we can keep it organized

**Comment by xinyil** [comment]
- text in S are M bold
- refer to zeplin and use Menu.svg for S menu button (in github sitemedia folder)
- the menu button will become close button when expanded
- remove the shadow and backgound color in S

**Comment by xinyil** [comment]
In Safari
- menu icon in S is missing
- the text in M has a strange weight change when the mouse moves out from one link.
- text color has not been changed to black
<img width="558" alt="screen shot 2017-11-22 at 12 57 14 pm" src="https://user-images.githubusercontent.com/17734456/33142528-e35e9310-cf84-11e7-95fd-aa82ca30b915.png">
![navm](https://user-images.githubusercontent.com/17734456/33142641-31af0ad6-cf85-11e7-8b0c-4070db6785b8.gif)

**Comment by xinyil** [comment]
Update after redeploying:

- seems like the weight shift problem noted above is only a Safari issue
- normal status of link text is still in grey

**Comment by thatbudakguy** [comment]
link text should now be full black by default.

**Comment by xinyil** [comment]
<img width="983" alt="screen shot 2018-04-05 at 11 46 29 am" src="https://user-images.githubusercontent.com/17734456/38376681-269d8586-38c7-11e8-803a-e2383ccce9da.png">
we might want to give M and S nav a white background to avoid such case
<img width="543" alt="screen shot 2018-04-05 at 11 46 39 am" src="https://user-images.githubusercontent.com/17734456/38376683-28d1a486-38c7-11e8-8f2c-74c7ec61a87f.png">
in S, the nav bar including menu, derrida logo/home button, and search icon should stay to the top.

**Comment by thatbudakguy** [comment]
bg is white now on <XL screens. the menu, search, etc. stay on top correctly for me in all browsers already; can't duplicate that last screenshot.

**Comment by xinyil** [comment]
- on S the whole nav bar should have fixed position at the top
- fix the blue space on S
<img width="500" alt="screen shot 2018-04-06 at 11 13 01 am" src="https://user-images.githubusercontent.com/17734456/38429176-acd1a3d4-398b-11e8-8b66-833658024a8d.png">

- where is the close button now? current:
<img width="191" alt="screen shot 2018-04-05 at 11 36 50 am" src="https://user-images.githubusercontent.com/17734456/38376031-a95495de-38c5-11e8-872d-96effd79ca13.png">
this gif is a capture of how it used to be:

![underline-animation](https://user-images.githubusercontent.com/2983582/31459001-c6568e1e-ae8f-11e7-879c-2f7ded09c79f.gif)

**Comment by xinyil** [comment]
Navigation on M seems broken, and you can scroll horizontally 
![reference-nav](https://user-images.githubusercontent.com/17734456/39431750-9e45cae8-4c5f-11e8-9ea2-55ff97fbff6a.gif)

**Comment by rlskoeser** [comment]
I can't duplicate the horizontal scroll, but the menu close icon and blue line are still happening.

**Comment by rlskoeser** [comment]
Currently mobile nav menu button is fixed but menu bar is not.

![screen shot 2018-05-08 at 10 09 31 am](https://user-images.githubusercontent.com/691231/39762216-1323e018-52a8-11e8-8949-97b8b9d21fcc.png)

**Comment by thatbudakguy** [comment]
Tried to fix as many of these as I could and still keep the nav looking sane. The X icon thing is unfortunately way harder than it should be because the entire button/icon is being added via some javascript I can't control that MDL is doing based on a `layout` class on the body (...I think). The generated icon doesn't use a class either; it just looks like a unicode glyph to me...decided not to pursue because it was taking too much time to track down.

**Comment by rlskoeser** [comment]
Drop-down mobile nav menu is still not showing when I am scrolled part of the way down the page.  It's white on the home page but not on secondary pages.

**Comment by thatbudakguy** [comment]
Colors and background look correct for the mobile nav. However, both the "X" and the text in the dropdown menu for what is being searched is invisible when on the homepage (but looks fine on other pages).

homepage:
![screen shot 2018-10-08 at 10 01 38 am](https://user-images.githubusercontent.com/4924494/46613571-915c5580-cae1-11e8-9ef7-d657123c916d.png)

elsewhere:
![screen shot 2018-10-08 at 10 02 04 am](https://user-images.githubusercontent.com/4924494/46613582-9a4d2700-cae1-11e8-9886-ff9dd7f9c9b5.png)

**Comment by thatbudakguy** [comment]
Looks good now.
