### ISSUE TITLE
As a user, I want to see a visualization of references by chapter in Derrida's work so that I can get a sense of how references are distributed through the work.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#78]
## Notes for testing
Updates 10/20/2017: updated so references by chapter is the default display, updated the label to make it more clear and more specific.

**Comment by rlskoeser** [comment]
I have some questions for @xinyil about how we want the URLs for these to be organized / how to think about it to eventually support multiple Derrida works, but for now I think it's functional enough to call development complete.

**Comment by araiffe** [comment]
There is a problem with this in the sense that multi-author works are inserting a dot next to each author of the book each time a specific chapter of the book is cited, even though a dot is only required next to the author who wrote the specific chapter that was cited.
The issue is most flagrant for _L'écriture et la psychologie des peuples_ which has many authors, some of whom are infrequently cited, or not cited, by Derrida, and nonetheless which appear to be amongst the most-highly-cited authors in the visualization page because so many dots appear next to all of their names.

**Comment by rlskoeser** [comment]
@araiffe this is helpful - I saw those multi-author works in the lists and wondered about them, but didn't think about the implications for other parts of the site.

Can you provide a couple of examples of book sections within that book for us to work with?  When I search on the example you provided I'm only finding the book record.

**Comment by araiffe** [comment]
@rlskoeser Unless I've inadvertently overlooked one, I believe that the sections are as follows: "La grande invention de l'écriture" by Marcel Cohen, "Histoire de l'écriture" and "Les sémites et l'alphabet" by James Février, "Les écritures indiennes" by Jean Filliozat, "La Chine. Aspects et fonctions de l'écriture" by Jacques Gernet, "L'écriture cunéiforme et la civilisation mésopotamienne" by René Labat, "L'Asie mineure. Les Hittites, peuple à double écriture" by Emmanuel Laroche, "L'écriture et le droit" by Henri Lévy-Bruhl, "La civilisation égéenne" by Olivier Masson, "Les Primitifs. Signaux et symboles" by Alfred Métraux.

**Comment by rlskoeser** [comment]
@araiffe I was going to respond but recognized the conversation really was specific to #93, so I've moved the conversation there. I don't think you can have tested this one since you haven't tested #56 yet.   I'm going to update the labels to reflect that.  I'll update the notes for testing to make it clearer how to access this visualization.

**Comment by araiffe** [comment]
@rlskoeser sorry rebecca, i don't know how that happened.

**Comment by kac3** [comment]
@rlskoeser Chapters have been entered and this seems to be working well, though -- perhaps a comment more for @xinyil -- the text of the chapters is long, so it gets bunched up and is not super easy to read

**Comment by rlskoeser** [comment]
I'm going to mark this one as tested needs attention and flag it for Xinyi to see if she wants to make any adjustments to the layout.

**Comment by rlskoeser** [comment]
@kac3 @araiffe we've updated the styles, please test again.

**Comment by kac3** [comment]
@rlskoeser @xinyil Looks fantastic!

**Comment by kac3** [comment]
@rlskoeser Reopened to ask: would it be possible to change the header from "Instance of Reference" to "References"?

**Comment by rlskoeser** [comment]
@kac3 sure, it's easy to change the label.  I wondered if that was clear or specific enough and meant to ask.   Perhaps something like "view by page/chapter in _De la Grammatologie_" ?

**Comment by kac3** [comment]
@rlskoeser I like that idea very much! How about "view by chapter in _De la grammatologie_"?

**Comment by rlskoeser** [comment]
@kac3 that sounds great to me. Thanks!  I'll leave this open until we've had the chance to make the update so you can review it when you're looking at other items.

**Comment by araiffe** [comment]
Tested, looks good to me.
