### ISSUE TITLE
Citation, Annotation, Library - LMS - book title display, clear all button, sorting buttons 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#81]
<img width="1099" alt="screen shot 2017-08-17 at 4 05 17 pm" src="https://user-images.githubusercontent.com/17734456/29432077-3150ed52-8368-11e7-9140-ed778fe1bb64.png">

<img width="720" alt="screen shot 2017-08-17 at 4 22 33 pm" src="https://user-images.githubusercontent.com/17734456/29432194-acc8d882-8368-11e7-8ca5-5e875ff77775.png">

**Comment by kevinglover** [comment]
@xinyil How do we want to style the rollover style for the sorting button?

**Comment by rlskoeser** [comment]
@kevinglover is it possible to use a radio button for the sort options?  Could that be styled to look like Xinyi's design?  (Open to another form element if there's a better option, but would like to generate this from the form if possible.)

**Comment by xinyil** [comment]
@kevinglover Can we make it the same as active? I also noticed that all the text that are supposed to be black are somehow a dark grey.

**Comment by xinyil** [comment]
<img width="1261" alt="screen shot 2017-09-08 at 11 25 49 am" src="https://user-images.githubusercontent.com/17734456/30218958-8f663bbe-9488-11e7-9260-3799fe37af35.png">

Sorry I missed this one before:
the style of hint text is bolded

**Comment by xinyil** [comment]
The ideal behavior is that when you go one level back in the breadcrumb, you won't lose active search and filters if you have any.

One live example:
https://www.shopspring.com/lifestyle/home/home_decor/decorative_pillows?priceRangeMax=50&refineFlags=on_sale
<img width="355" alt="screen shot 2017-08-24 at 11 21 13 am" src="https://user-images.githubusercontent.com/17734456/30220966-8df0b794-948f-11e7-8ecb-457244ee6742.png">

**Comment by xinyil** [comment]
<img width="356" alt="screen shot 2017-10-09 at 11 30 35 am" src="https://user-images.githubusercontent.com/17734456/31345938-4aff92f2-ace5-11e7-937a-0ca19eddb985.png">

clear all button has not been fixed
