### ISSUE TITLE
Page number display, author name display

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#82]
<img width="715" alt="screen shot 2017-08-17 at 4 10 30 pm" src="https://user-images.githubusercontent.com/17734456/29433697-484a6000-836e-11e7-8749-439642fb00d4.png">

- If the citation spreads on a range of pages, the page number will display as, for example pp. 87–89    If it’s on a single page, then p.87   We should make a decision on how to handle this in the database and perhaps update instructions for data entry.

- Add space between page number and page location in DG, for example "p. 147  b" 

- Author names will be displayed as First Last at all occasions other than the filter

**Comment by rlskoeser** [comment]
@xinyil how do you want to handle multiple authors?  Or very long titles?

**Comment by xinyil** [comment]
@rlskoeser maybe first author's name followed by et al. ?  not sure if there'd be enough space for all

**Comment by rlskoeser** [comment]
Restricted to two authors max plus et al. if there are more.  Search for ecriture to find an item with a lot of authors to see how it displays.
