### ISSUE TITLE
Visualization - SML

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#83]
https://test-derrida.cdh.princeton.edu/references/histogram/

![screen shot 2017-08-17 at 4 06 08 pm](https://user-images.githubusercontent.com/17734456/29434486-31bc5656-8371-11e7-9a4b-85f7c5dd5ead.png)

**Comment by xinyil** [comment]
<img width="1252" alt="screen shot 2017-09-08 at 11 07 45 am" src="https://user-images.githubusercontent.com/17734456/30218114-2bab0cb4-9486-11e7-9243-d1c402ca48b1.png">

extra grey box exists at top

**Comment by xinyil** [comment]
<img width="1328" alt="screen shot 2017-10-09 at 11 57 48 am" src="https://user-images.githubusercontent.com/17734456/31347115-43515eb0-ace9-11e7-8033-2ed7d2a6ca38.png">

- change header min-width to 15rem to enhance chapter title display
- set title in italic

<img width="1072" alt="screen shot 2017-10-09 at 12 00 22 pm" src="https://user-images.githubusercontent.com/17734456/31347197-87675488-ace9-11e7-9a48-b9e70e1d9fa6.png">

- "part I" section title shouldn't be closer to the previous section


- in chrome, some the dots are being clipped from different sides

<img width="613" alt="screen shot 2017-10-09 at 12 03 03 pm" src="https://user-images.githubusercontent.com/17734456/31347280-da808e64-ace9-11e7-939b-3fa28b21e5a7.png">

**Comment by xinyil** [comment]
I can't seem to access the visualization page - it's blank now

**Comment by rlskoeser** [comment]
@xinyil I tried to change the link to make the viz by chapter the default but I broke it.   If you click the link again I think you'll get it?

**Comment by xinyil** [comment]
set chapter title in italic. see screenshot above.  

@rlskoeser nope still can't!

**Comment by rlskoeser** [comment]
I fixed the bad nav link, should display properly now.

Xinyi if you are happy with the revised spacing, we can mark #78 / #93 as ready for the project team to review again.

**Comment by xinyil** [comment]
@rlskoeser please do

**Comment by rlskoeser** [comment]
This was tested by the team and they're happy with the revised labels spacing, so I'm going to close this one.
