### ISSUE TITLE
Search results - SML

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#84]
<img width="1234" alt="screen shot 2017-08-17 at 5 25 20 pm" src="https://user-images.githubusercontent.com/17734456/29434596-a3d68090-8371-11e7-8127-a1785d2ff3f1.png">

<img width="1091" alt="screen shot 2017-08-17 at 5 28 55 pm" src="https://user-images.githubusercontent.com/17734456/29434601-afb8fd5c-8371-11e7-820a-67ba9c1a9431.png">
- Display results in one column for S 

- note the the first category is Library books and it has a different layout than the other two kinds of "cards"

**Comment by kevinglover** [comment]
@xinyil Is the"View All" text part of the link or just plain text?

**Comment by xinyil** [comment]
the arrow plus the text are the link

**Comment by kevinglover** [comment]
Ok, so there's just no indication it's a link, right?

**Comment by xinyil** [comment]
no underline
arrow and text turn blue for rollover stage

**Comment by rlskoeser** [comment]
@kevinglover does it make sense to wait and test search results with the new Solr functionality, or do you want to get the styles and templates cleaned up first?

Xinyi's note here about the book having a different layout is something I noticed too: the book result is very minimal, just title/author/date/copy.

**Comment by xinyil** [comment]
<img width="1310" alt="screen shot 2017-09-06 at 1 48 42 pm" src="https://user-images.githubusercontent.com/17734456/30126654-9eb10498-930a-11e7-8e5a-2a0d830eb8ed.png">

- Display results in one column for small viewport 
has not been fixed

**Comment by xinyil** [comment]
Can't access https://test-derrida.cdh.princeton.edu/search-results

**Comment by xinyil** [comment]
<img width="1031" alt="screen shot 2017-10-09 at 1 03 40 pm" src="https://user-images.githubusercontent.com/17734456/31349724-618d6370-acf2-11e7-9262-3672d48b2c43.png">

- "view results" in universe


- consider changing title "Reference" to red so it's more apparently a difference section?

**Comment by kevinglover** [comment]
@xinyil Based on your design, Reference looks very much like a separate section already. We could try restyling the headers for each section to further distinguish them

**Comment by xinyil** [comment]
font size for result numbers are 
12px = 0.75em

**Comment by kevinglover** [comment]
@xinyil Do you mean the whole "view results" part or just the number?

**Comment by xinyil** [comment]
@kevinglover <img width="1031" alt="screen shot 2017-10-09 at 1 03 40 pm" src="https://user-images.githubusercontent.com/17734456/31349724-618d6370-acf2-11e7-9262-3672d48b2c43.png">

**Comment by kevinglover** [comment]
@xinyil Just to be completely clear - the Unicode Arrow `→` should not be 12px?

**Comment by xinyil** [comment]
@kevinglover Sorry if I confused you. The Unicode Arrow should be 12px, just because Universe doesn't have this glyph, it's been rendered in Lucida Grande in my Sketch.
