### ISSUE TITLE
Footer - LMS 

### ISSUE THREAD

**Issue by xinyil** [Princeton-CDH/derrida-django#88]
<img width="1196" alt="screen shot 2017-08-17 at 9 03 07 pm" src="https://user-images.githubusercontent.com/17734456/29440093-211849ee-8390-11e7-8e5c-80b23dc31fb0.png">

**Comment by rlskoeser** [comment]
@kevinglover the images are in the footer now, but they still aren't links.

**Comment by kevinglover** [comment]
@rlskoeser My mistake; I missed that. The links are there now. If @xinyil is ok with the layout, we can close this issue after testing.
