### ISSUE TITLE
Library list filtered by author

### ISSUE THREAD

**Issue by kevinglover** [Princeton-CDH/derrida-django#89]
Clicking on the author in a collection item view will open a filtered library page of that author's books.

<img width="260" alt="screen shot 2017-08-17 at 9 00 40 pm" src="https://user-images.githubusercontent.com/17734456/29439967-58c8b690-838f-11e7-8ea4-ceaf48fb71b5.png">

**Comment by rlskoeser** [comment]
@kevinglover I've made the author names into links.  Do you want to tweak the link style?

**Comment by kevinglover** [comment]
@rlskoeser Nice! I'll work on this real quick

**Comment by kevinglover** [comment]
@rlskoeser This won't preserve the orderBy param. Is that ok?

**Comment by rlskoeser** [comment]
@kevinglover yes, I think that's fine

**Comment by xinyil** [comment]
<img width="925" alt="screen shot 2017-10-09 at 11 28 47 am" src="https://user-images.githubusercontent.com/17734456/31345856-10e8b706-ace5-11e7-900e-4194952b79f0.png">

rollover status of author names: add the same underline as book title

**Comment by xinyil** [comment]
the underline style doesn't seem to be live on the current test site.
