### ISSUE TITLE
As a user, I want to filter the list of books cited in Derrida's works so that I can narrow the list based on my interests.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#90]
## Notes for testing
- Updated 9/28: filter items are now alphabetically sorted, using pagination preserves active filters.
- Styles for the filters are still being worked on, but Xinyi will sign off on the design elements. 
- Date filters will be handled separately because implementing that requires a range facet query #122 

---

Filter on:
* author
* subject
* language of publication
* place of publication
* original publication year
* edition year
* printing year
* publication type
* cited in Derrida work

test fixes:
- [x] sort facets by alpha instead of count
- [x] preserve filters after clicking to next page

**Comment by rlskoeser** [comment]
@xinyil some questions for you about the filter functionality. 

* Where is the filter submit button, or do you expect filters to be applied (trigger a submit) as soon as they are selected?
* Are facet counts in the filters based on current selection or total count? (playing with it in my prototype implementation makes me think total would make more sense)
* What does "clear all" do?
* What do alphabet letters in the author selection do?

**Comment by xinyil** [comment]
@rlskoeser 
Where is the filter submit button, or do you expect filters to be applied (trigger a submit) as soon as they are selected?
- they will be applied after been selected


Are facet counts in the filters based on current selection or total count? (playing with it in my prototype implementation makes me think total would make more sense)
- yes I think total count makes more sense. we can test this with more people tho.

What does "clear all" do?
- clear all in a filter dropdown will reset this filter
- clear all near sorting buttons will remove all active filters/search 

What do alphabet letters in the author selection do?
- narrowing down displayed names to which begins with that alphabet

Do the extant/containing annotation filters toggle between all titles and only those that are extant or annotated? (i.e., there's no way to filter to non-extant/non-annotated titles)
The tagline at the top says that only extant titles are included: is that the desired behavior, and if so does that make the extant filter irrelevant?
- when the toggle is off, it displays non-extant books. Although in this phase non-extant book won't have a book "card", Katie included this option for future usage perhaps.

**Comment by araiffe** [comment]
In the filters, why aren't the authors appearing in alphabetical order in the dropdown menu? This appears to be a bug.

**Comment by rlskoeser** [comment]
The filters are all sorted by the number of matches so that authors, subjects, languages, etc with lots of matches appear first.  This is fairly standard with facets (and the default in Solr), but I see now in Xinyi's design that all the facets are sorted alphabetically.  Should be easy enough to switch!

**Comment by araiffe** [comment]
tested and appears to be working
