### ISSUE TITLE
As a user, I want to change how the list of books is sorted so that I can browse the list in different ways.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#91]
## Notes for testing
Updates 9/28:
- default sort now applied properly when you first load the page
- new option to sort by title
- sort & filter options now preserved when you follow pagination links
- initial list now restricted to extant, cited books only
- now sorts on and displays the same date (print year if known, otherwise copyright year)
- I'm probably not handling collected works / book sections properly - if a book section is referenced, the collected work should show up in the library, right?  A test case of this (references on the book sections, none on the collected work) would be helpful.  (Related to the cleanup we discussed on #93)

----
order by:
* author
* _title_
* publication date (oldest to newest)
* publication date (newest to oldest)

**Comment by rlskoeser** [comment]
@xinyil a question and a problem.

Do you know which year I should use for publication date?  Is this the same as original publication year from the filters?

Solr can't sort on a multi-valued field, and our books can have multiple authors.  

I also wondered if sort by title would be useful.

**Comment by xinyil** [comment]
@rlskoeser I went back to the email from Katie, and the sorting options for books are:
sort by Author (alphabetical); Publication Date (oldest to newest/newest to oldest)

I think it would be original publication date, and if the language is causing confusion, we can change it to Origin Publication Date.

Sorting by title sounds useful - I was kind of assuming that's the default, and of course there has to be a way to go back to the default.


It might worth getting the project team's attention on the limitation of sorting by author.

**Comment by araiffe** [comment]
The sort by date feature doesn't seem to be working -- the dates displayed don't appear in chronological order.

**Comment by rlskoeser** [comment]
@araiffe the dates are confusing because we have so many of them.  I'm currently sorting on _work year_ but the date displayed on the card is the _copyright year_ - but should that be the print year if we have one, to distinguish different editions?  I think the development team had some discussion about this and implemented it based on the information we had in our notes.

Please let me know if I should use a different year for sorting and also which year (or years?) should displayed on the card.

**Comment by araiffe** [comment]
@kac3 what is your opinion on the type of date that should be used to sort? I think it's confusing to have the sort order be different from the date visible to the user under each work on this screen.

**Comment by kac3** [comment]
@rlskoeser @araiffe I think it should be print year if known; otherwise, copyright year.

There is another important issue I'm seeing here, though: currently **all** instances are displaying in the library view -- books that are not extant in the JD library collection, and instances that are in the database already as Book Sections collected in larger works -- instead of just extant books.

**Comment by rlskoeser** [comment]
Thanks for clarifying which dates to use, I can update that and use the same date for sort and display.

And thanks for catching the fact that I am not filtering the list correctly! I just checked with Xinyi, and I think I understand better. The design currently includes a toggle for is extant and a filter for item type (book, book section, journal article) - but I think both of those should go away since we only want to display extant books.

Xinyi and I also discussed a while back - would you also like the option to sort by title?

**Comment by kac3** [comment]
Perfect -- thanks so much. 

I think the only item we want to show other than extant books are extant copies of journals. In other words, we want the Derrida's library section to be like a bookshelf where you see individual physical objects extant in the collection. It might be worth keeping a book/journal filter, but, yes, dropping the book section option. 

An option to sort by title would be terrific! I found myself wanting that as a user during testing.

**Comment by araiffe** [comment]
@rlskoeser @kac3 I notice one problem in the "Derrida's Library" list of books, which is that the titles are being pulled from the "Platonic Works" (Works) section of the back office rather than from the "Instances" section. In the Platonic Works section we're listing books by their original titles in their original languages, but this has the effect of making the copy of the English translation of Ernst Cassirer's _The Philosophy of Symbolic Forms_ be listed as _Philosophie der Symbolischen Formen_ in the Library view. 

Another remark - the dates still seem slightly wonky (i.e. the first thing that shows up is _Le problème de l'être chez Aristote_ when sorted by Oldest to Newest, whereas works by Plato appear after) but that could be a problem with our data?

**Comment by rlskoeser** [comment]
@araiffe some responses to the concerns you raised:

I checked on the Platonic works titles vs instances titles - the Cassirer title you mentioned didn't have an alternate title set on the instance record, and when that's the case the system uses the work title.  I tested this by adding an alternate title in the admin site.  If you can find other examples to check that would be helpful.

The items you're seeing first when you sort oldest to newest don't have any dates on the Instance record, and the current logic is to use Instance print year if available with a fallback to instance copyright date.  Should I add a third fallback to use the work year if neither of the instance dates are set?

**Comment by araiffe** [comment]
@kac3 Should I go in and add alternate titles to all of these works? I suspect this might be part of the delayed clean-up of the instances data.

@rlskoeser I think it seems logical (at least on paper) to add a third fallback to the work year but I'm not sure what the implications of this would be in a logical sense (i.e. some Plato being listed as -350 and others as 1950…). @kac A penny for your thoughts? It might be that this is a question of unkempt data that will be rendered moot once the aforementioned clean-up takes place…

**Comment by kac3** [comment]
@rlskoeser @araiffe I think both of these issues will be resolved once we've gone through and cleaned up the data, because we should always have a copyright date at the very least for any given instance.  They just aren't all in the system yet.

**Comment by rlskoeser** [comment]
@kac3 @araiffe please do any data clean up work in the production system and we'll refresh the test site when you tell us.  If you want to make some test updates in the test site to confirm what we suspect, that adding the dates and alternate titles fixes the display, that's fine - just keep in mind you'll need to also do it on the production site.

I also wondered about the implications of using the work date as a fallback, since it seemed potentially problematic in some cases.

**Comment by araiffe** [comment]
@kac3  can I mark this as tested and closed for the time being?
