### ISSUE TITLE
As an admin, I want to view and edit the unique url slug for each work instance so that I can manage the public urls for library works displayed on the site.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/derrida-django#92]
## Background
A "slug" is a short label with only letters, numbers, and hyphens used in urls (see https://docs.djangoproject.com/en/2.0/glossary/); we create these so that we can have semantic, readable urls for content rather than arbitrary numeric database ids based on the order that things were added to the database.
The slug format Ben and I came up with is based on author last name, title, year, and copy for cases where there are multiple copies of the same exact edition.
Note that changing a slug for published content means the old url will break, which is bad - so we want to avoid this if possible, or create redirects if we need to rename something (but the best solution is to set them to something good to start with).

## Notes for testing
- There is a data migration that will generate unique slugs for all the content already in the system; please check and review some of these in the admin interface on the edit form for a work instance (they're also being used in the public urls)
- Please test creating a new work instance: if you leave the slug field blank and save, the slug should be automatically generated for you.  If you are creating a new copy of an existing instance/edition, the slug will use the copy letter if you specify it; otherwise it will generate a copy value based on the existing copies already in the database (i.e., if there are already A, B, and C copies, the new one will be marked as D).
- You can edit an existing slug to change it (feel free to test), but there should be help text to warn you to do this with care.

## Notes for development
As an admin user, I want to be able to set the canonical slug for instances of works in Derrida's library, with verification that the slug is valid and that changes I make to relevant fields can be reflected with warnings about changing the slug if the record already exists.

**Comment by rlskoeser** [comment]
@bwhicks this seems like it should have been part of a past release.  Did it get completed and not tested, or did we not implement it yet?

**Comment by bwhicks** [comment]
@rlskoeser When last I was looking at Derrida, this was at the team for their review. I think there was a similar issue that was approved and this may be a duplicate. I will check.

**Comment by kac3** [comment]
@rlskoeser Everything with the slugs is working great.  

However, I kept running into a problem every time I tried to create a new copy of an existing work instance.  I tried multiple works and kept getting an error message, and I'm not sure what the problem is.

![screen shot 2018-03-17 at 3 44 38 pm](https://user-images.githubusercontent.com/26174024/37559339-826b451e-29fa-11e8-8466-d0df1fdc8132.png)

**Comment by rlskoeser** [comment]
@kac3 is it possible you're running into #79? This is a bug that Ben and I identified, but hadn't prioritized for a fix (yet) because we weren't sure how important it was.  If it's a blocker for testing, then we can prioritize it for a fix.

**Comment by kac3** [comment]
@rlskoeser I think this might actually be a different bug.  It happens even when I try to change the copy field of an existing work instance (for example here, trying to set this as "b") that already has an associated work.

![screen shot 2018-03-26 at 11 24 25 am](https://user-images.githubusercontent.com/26174024/37915808-5b86f4f8-30e8-11e8-9f4e-cd43cf7e9b11.png)

**Comment by rlskoeser** [comment]
@kac3 thanks for reporting and documenting with screenshots.  I think the copy field requires an upper-case letter, but you ought to see help text to that effect, and the validation error should be more specific also.  We'll look into it.

**Comment by rlskoeser** [comment]
It looks to me that this is a different manifestation of the bug described in #79 - please test both that version and this and see if it resolves the problem you were seeing.

**Comment by kac3** [comment]
@rlskoeser Both this and #79 are working great!
