### ISSUE TITLE
As a user, I want to see an indication of which library books in the list are annotated so I can easily identify books with annotations.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#94]

**Comment by rlskoeser** [comment]
@kevinglover can you take this one on?  The Solr index should provide the flag you need to key on (there's a comment the template), and there is a preliminary design for how this should look (with a placeholder graphic) in Zeplin.

There's a similar visual indicator planned for annotated pages, so would be great if the styles were reusable for that.

**Comment by rlskoeser** [comment]
@kevinglover what do you think about adding alt text/title text for the icon as a way of providing a cue for what it means?  I know that won't help on mobile, but could be useful on desktop.

**Comment by kevinglover** [comment]
We can definitely do that. We could even style a tooltip to show the purpose of the icon. What do you think the test would say for these?

**Comment by rlskoeser** [comment]
@kevinglover perhaps  "contains annotations" ? That would be fairly consistent with the filter language

**Comment by rlskoeser** [comment]
@kevinglover I like the tooltip, thanks for adding it.  This one looks good to me, I'll mark it as ready for the project team to look at.

**Comment by kac3** [comment]
@rlskoeser @kevinglover Looks good!
