### ISSUE TITLE
As a user looking at a single book in the library, I want to see a list of other copies and editions of the same work so that I can see all the versions Derrida cited.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#95]

**Comment by araiffe** [comment]
@rlskoeser just to make sure, what steps should I take to ensure I test this properly?

**Comment by rlskoeser** [comment]
@araiffe sorry, I didn't add notes for testing!  Please look at the detail view for a couple of items that you know have more than one edition or copy and check that you can see the other copies listed, that they display correctly, and that you can click on the thumbnail to get to the detail page for the other item.  Please also look at the detail page for a couple of other items without other copies or editions of the same work to check that the section doesn't show up.

**Comment by araiffe** [comment]
tested and seems to be working properly
