### ISSUE TITLE
As a user looking at a single book in the library, I want to see a gallery of images for that book so that I see what it looks like and see sample annotated pages.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#97]
## Notes for testing
- overview images and insertions are identified based on the labels in Plum, so this will only work for books where the labels have been updated.  Try the Lévi-Strauss titles:
https://test-derrida.cdh.princeton.edu/library/?author=L%C3%A9vi-Strauss,+Claude
- annotated pages are identified based on the interventions that have been captured in the database, so the Saussure is a good one to check
- design includes 'relevant markings' but I don't think we have any content for that (let me know if I'm wrong)

**Comment by araiffe** [comment]
this appears to be working for the Lévi-Strauss titles (I checked _Anthropologie structurale_)

**Comment by rlskoeser** [comment]
@araiffe I forgot to mention in my email - I see you commented on this and added the label 'development complete'.  If you're through testing and satisfied that it works, please go ahead and close the issue so we know it's done!
