### ISSUE TITLE
As a user looking at a single book, I want to see the references to that work so I can get a sense of how Derrida used it.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#98]
## Notes for testing
- This is the 'reference' tab on the individual book detail page. 
- As of 3/8/2018, now correctly filters references to those associated with the current book.
- Please test that it includes references to book sections (i.e. check _L'Ecriture et la psychologie des peuples: actes de colloque_)

----

Add to the design in Zeplin: display total number of references in that book, using the same style from the reference list.

- [x] add sort options/logic 
- [x] style sort options to match form filters 
- [x] update search index for reference so that instance slug for references associated with book sections rather than works indexes on the book slug rather than the book section

**Comment by rlskoeser** [comment]
This seems to filter correctly on my dev site but not on the test site.

**Comment by araiffe** [comment]
This seems not to be working properly. When I click on "L'Œil vivant" by Jean Starobinski, I'm getting 29 results, many of which are citations or quotations of Plato's "Phèdre", Georges Charbonnier's "Entretiens avec Claude Lévi-Strauss" one citation from Descarte's "Discours de la méthode" and other quotes from other works by Starobinski ("La transparence et l'obstacle").

**Comment by rlskoeser** [comment]
@araiffe sorry about that - I noticed at some point that it wasn't working right on the test site but I wasn't easily able to identify the problem and then I forgot when I delivered it.  It's working properly on my development site.

@bwhicks when you're updating the unicode filter config, could you take a quick look at this?  It would be helpful to know if it's working on your dev site or not.  I checked the solr logs on the test server, and it reports that's filtering on `instance_slug` as I expect - but the results don't reflect that.

**Comment by bwhicks** [comment]
@araiffe @rlskoeser There was an issue with the deploy and some fun django-compressor cache folder nonsense. A reindex has this working as expected I believe.

**Comment by rlskoeser** [comment]
This is now filtering properly on the test site.

This should display references associated with book sections -  see Roussea's _Du Contrat social ou Principes du droit politique. Discours sur les sciences et les arts 3 Discours sur l'origine de l'inégalité parmi les hommes / Lettre à M. D'Alembert / Considérations sur le gouvernement de Pologne / Lettre à Monseigneur de Beaumont_ for an example.

**Comment by bwhicks** [comment]
Reference commits on #92 that I just pushed because I mixed issue number (for tests a documentation tweak)

**Comment by kac3** [comment]
@rlskoeser It does include book sections (I checked the infamous _L'écriture et la psychologie des peuples_), but there are some display issues with the author.  I'm seeing all section authors for some, and just the particular section author for others.  Is this a data issue?

Otherwise looking good!

![screen shot 2018-03-17 at 3 24 23 pm](https://user-images.githubusercontent.com/26174024/37559151-644ee430-29f7-11e8-898d-61f673260ee5.png)

**Comment by rlskoeser** [comment]
@kac3 yes, this is indeed a data issue.  If you pull up the work instance for _L'écriture et la psychologie des peuples_, you'll see that there are still 12 references associated directly with it rather than the sections.  It would probably be a good idea to test #164 to get a better understanding of what's going on here.  I think there may be at least one section with references that Alex missed; and if there are references to the book, you'll have to decide who you want listed for that (i.e., you may want to remove all the section authors from the work instance itself).
