### ISSUE TITLE
As a user, I want to filter the list of references so that I can narrow the results based on my interests.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/derrida-django#99]
## Notes for testing
- Year filters will be handled separately via #122 
- We may revise the layout some to clarify book attributes vs reference attributes, but the filter functionality is working.

Filter by:
- book is extant
- book contains annotation
- book contains corresponding annotation
- book author
- book subject
- book language of publication
- book original language
- book place of publication
- ~book original publication year~
- ~book edition year~
- ~book printing year~
- citation type
- derrida work

**Comment by araiffe** [comment]
@rlskoeser the filters seem to be working properly
